### ISSUE TITLE
Audio attachments possibly broken in simulator

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#1003]
Play button doesn't appear to work

<img width="279" alt="Captura de Pantalla 2021-07-08 a la(s) 10 29 31" src="https://user-images.githubusercontent.com/675558/124950123-c1f5b480-dfd7-11eb-916a-5c686ab7e2f4.png">

**Comment by ericnewcomer** [comment]
What browser and file type did you see this with?

**Comment by rowanseymour** [comment]
Uploading an [ogg file](https://commons.wikimedia.org/wiki/File:Example.ogg) on a Send Message action, and trying to simulate in Chrome.

**Comment by matmsa27** [comment]
The same error occurs on IVR Flow. I configured a card to play a message and I uploaded an ogg file. I tested in Brave Web Browser and Chrome and the audio doesn't play. Is there the same error or a new bug?

![image](https://user-images.githubusercontent.com/10725273/128100099-98d58323-69ba-414b-95cf-be96c5982a4f.png)
