### ISSUE TITLE
Not able to save changes in the wait for response node even after correcting the validation error

### ISSUE THREAD

**Issue by mdshamoon** [nyaruka/floweditor#1009]
**Describe the bug**
Not able to save the changes in the `wait for response` node even after correcting the validation error

**To Reproduce**
1. Open a `wait for response` node
2. Add a symbol like `*` in the result name and it will give a validation error
3. Correct the result name so that there are no validation errors
4. Try to press OK. It does not close the node and gets stuck.

**Expected behavior**
It should be able to save after removing the validation errors

**Comment by rowanseymour** [comment]
Can reproduce, thanks for the detailed report!

**Comment by mdshamoon** [comment]
@rowanseymour can I pick up this issue?

**Comment by rowanseymour** [comment]
We don't actually accept PRs on this repo. We'll get to this soon tho.

**Comment by mdshamoon** [comment]
Alright, Thanks.

**Comment by dlobo** [comment]
> We don't actually accept PRs on this repo. We'll get to this soon tho.

Would be great if you'll can revisit this rule and allow other folks to contribute a PR under your guidelines. Seems beneficial for all parties involved, IMHO

**Comment by ericnewcomer** [comment]
Sorry for the delay, taking this up now.
