### ISSUE TITLE
Create subflow from currently selected nodes in a flow.

### ISSUE THREAD

**Issue by cromulus** [nyaruka/floweditor#1017]
Hi!
Refactoring flows would be much easier if it was possible to select nodes in a flow and create a sub-flow out of those nodes.

Thanks!

**Comment by mdshamoon** [comment]
Hey are you guys planning to take this up sometime soon. Would be a great help for breaking up long flows.

**Comment by ericnewcomer** [comment]
This wouldn't be a super difficult thing to do, but this is actually a RapidPro feature, not an editor feature as the editor doesn't have a concept of flow creation, etc.

It's just a matter of making the selection available to the containing page. That may already be possible with jsplumb as it is. If not, we could certainly look at firing a custom event when nodes are selected that the container page can listen for.

**Comment by rowanseymour** [comment]
One way to implement this could be passing node UUIDs to mailroom's clone endpoint and telling it only include those in the cloned output.

**Comment by ericnewcomer** [comment]
Yup, something like that could make sense. I think the actual rapid bits should be pretty easy, so really just a matter of exposing the selection sufficiently on this side.

**Comment by ericnewcomer** [comment]
I've added the necessary event from the editor to make this possible. @mdshamoon, you guys should be able to open a PR using this and then modify the mailroom clone feature to glue things together.
