### ISSUE TITLE
Shouldn't show Expired exit for IVR enter flow actions

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#1034]
When IVR flows expire, calls are hung up and we don't resume parent flows.

<img width="230" alt="Captura de Pantalla 2022-01-26 a la(s) 13 52 24" src="https://user-images.githubusercontent.com/675558/151253168-87bae3c6-f16d-4de6-9da5-5374083de001.png">

**Comment by susanm74** [comment]
ingresar en un flujo => enter a flow

**Comment by rowanseymour** [comment]
@rowanseymour sorry what I meant in the original comment is that _we currently hang up calls and don't resume parent flows_, thus the Expired exit is never used in an IVR flow. Thus the only thing needed here is not showing it in the editor for IVR flows.

**Comment by ericnewcomer** [comment]
Fixed in #1086
