### ISSUE TITLE
Extra Input Bug

### ISSUE THREAD

**Issue by colenewcomer** [nyaruka/floweditor#1043]
Repro steps:
-Set up any kind of flow
-Use the flow tester and run to the 'Exited flow' text at the end
-type in and send any extra input

These steps will cause the flow editor to turn into a blank white page

Example:
<img width="298" alt="Waiting for reply" src="https://user-images.githubusercontent.com/96800852/154163173-5f9b0e36-c6bd-4ba8-86ba-9cbef786ba95.png"><img width="1349" alt="Screen Shot 2022-02-12 at 2 27 38 PM" src="https://user-images.githubusercontent.com/96800852/154163254-869bf616-b229-4b91-938c-bb4373eca814.png">

**Comment by ericnewcomer** [comment]
Nice find:

- Please include a screenshot of the console error if there is one
- No name to put bug in the title
- Without getting too verbose, try for clearer title "Message in simulator after flow exit clears entire page"
