### ISSUE TITLE
Handle errors from media upload endpoint

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#1067]
This endpoint will now send back responses like:

```json
{"error": "Unsupported file type"}
```

and 

```json
{"error": "Limit for file uploads is 25 MB"}
```

**Comment by susanm74** [comment]
@rowanseymour qq re: supported vs. unsupported file types - i see within the test snapshots that a user can upload an "upload" (what i assume is anything that's not the other 4), an image, audio, video, or a pdf, and i see that some tests allow ex. mp3 for audio and ex. mp4 for video - is there a reference somewhere with a list of supported file types for each upload option type? (not needed for pdf i suppose, but for an image, audio, video, and catch-all "upload" this could be helpful if there's a spot where it's defined)

**Comment by rowanseymour** [comment]
The Django endpoint this is calling is https://github.com/nyaruka/rapidpro/blob/47520f04e8de69ac2683e50a0849111250641b2a/temba/msgs/views.py#L1019. And it can now return either a valid media upload object, or an error response like above - but the editor code isn't setup to handle an error response so that's the only thing you need to fix.

**Comment by rowanseymour** [comment]
Added
