### ISSUE TITLE
Emails show with encoded characters in simulator output

### ISSUE THREAD

**Issue by morrismukiri** [nyaruka/floweditor#1077]
How to replicate: Create a flow with "send email". The recipient email address seems to be url-encoded.

Here's an example on the simulator

<img width="1490" alt="Screenshot 2022-10-07 at 10 31 53 AM" src="https://user-images.githubusercontent.com/804653/194543631-a991e680-cc2c-4385-a74f-9494d1cfb38b.png">

**Comment by ericnewcomer** [comment]
Can you give a bit more details in how it is broken? I see the encoding issue in the simulator, but is that a display issue or are you seeing other issues?

**Comment by morrismukiri** [comment]
The same happens when the flow is run, where you can't send an email from the flow. The simulator gives a hint at possible causes.

**Comment by ericnewcomer** [comment]
We aren't seeing an issue with emails actually being sent. Is this a TextIt account? If you reach out to our support there, we can help you track it down.
