### ISSUE TITLE
Don't allow selecting URNs in Start Somebody Else actions

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#1090]
We recently removed specifying groups, but I think we should also remove URNs and make that omnibox contacts only. We allow starting flows by URN in places like the API as a convenience - where the contact may or may not exist and can be created from the URN if necessary. But flows don't run against URNs, and there's no guarantee that the URN you specify is the one we'll use for messages in the flow. 

Using contacts in flows also allows contacts to be tracked as dependencies - flow inspection currently tracks these like any other dependency tho we don't expose that anywhere in the UI.

**Comment by ericnewcomer** [comment]
What about expressions?

**Comment by rowanseymour** [comment]
Ayy forgot about those - you can still match against a group name with an expression. Hmm...

**Comment by rowanseymour** [comment]
The other thing is that expressions are janky and considered legacy - we want people to use a query to explicitly match a contact by uuid or URN type. Maybe need to investigate what's actually being used right now.

**Comment by rowanseymour** [comment]
I think we want to prevent new uses of expressions in the editor and start tracking existing uses as flow issues https://github.com/nyaruka/goflow/pull/1141. We can't easily migrate them because we don't know if they evaluate to a group name or a contact UUID or a phone number.
