### ISSUE TITLE
Result categories should be limited to 128 chars

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#1185]
On a Wait For Response modal, result categories are limited to 36 chars. On the Save Flow Result modal, there's no such restriction allowing categories longer than 128 chars which blows up trying to save `FlowCategoryCount` rows.

**Comment by susanm74** [comment]
@rowanseymour let me know if you need me to pause on other stuff to look into this

**Comment by susanm74** [comment]
👍
