### ISSUE TITLE
Translations are not removed from the flow revision even after removing the node from the UI

### ISSUE THREAD

**Issue by mdshamoon** [nyaruka/floweditor#1216]
**Describe the bug**
Translations are not removed from the flow revision json even after removing the node from the UI

**To Reproduce**

1. Create a flow with multiple nodes
2. Add a translation to a send message node
3. Delete the  node
4. Translations still exists for that node in the flow revision json

**Expected behavior**
The translation for the node should be removed from the revision json

**Comment by ericnewcomer** [comment]
Thanks for filing this. I can confirm this is indeed an issue. We'd be open to a PR to address.
