### ISSUE TITLE
Character counter tweaks / help

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#149]
Couple comments:
 * I don't think we need the question mark, we can just show the pop up when you go over the numbers
 * The help text should use the numbers that are currently set instead of static ones

![flow2 2018-02-26 11-08-12](https://user-images.githubusercontent.com/168067/36681017-725c2798-1ae5-11e8-9693-1fae5e57b0e0.png)

**Comment by ycleptkellan** [comment]
sounds good to me. @ericnewcomer?

**Comment by ycleptkellan** [comment]
WIP here for reference https://github.com/nyaruka/floweditor/pull/151
