### ISSUE TITLE
Make people opt out of saving results

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#156]
I think when we were first redoing the editor we were kinda in this mode that results are heavy to save for flows and we should make the user explicitly tell us they want to save. I think that's going to be a bit of a disaster if we ship that because I can just predict that the majority of people are going to space about saving a result and therefore lose data.

So I think at least for any ruleset that is a "wait" we need to default to saving so that they don't lose data that they realize only later they don't have and can no longer recover.

Note that our schema has changed since then too, so we care a lot less about saving results than we did, so having a bias towards keeping data is good. (though I think from a convenience point of view not requiring names for non-waits still probably makes sense)

**Comment by ericnewcomer** [comment]
Ya, I think that totally makes sense.

Should we require a name or just provide one for them like we do in the old world? ie, "Response 5", etc. I think the pre-filled response that they can edit served us well and is worth keeping. thoughts?
