### ISSUE TITLE
Dragging an arrow connected to ruleset, then back to same ruleset creates dialog

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#160]
1. Connect an action to a ruleset
2. Drag arrow from arrowhead off of ruleset away from ruleset so it detaches, then reconnect to ruleset
3. You get a dialog for an action set

Expected:
reconnects to ruleset

This seems to do the same thing for ruleset->actionset, seems to always happen if just dragging back to the node it came from really.

**Comment by ericnewcomer** [comment]
Definitely have noticed this bug too. We had this same bug in the old editor at one point too. If memory serves, this is due to which connection event we are hooking into on the jsplumb side. I believe there's one that doesn't fire in this case that we should be using.
