### ISSUE TITLE
`Loading` shown when you select ContactField or Flow in editor

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#207]
Given an "Update Contact" action or "Start Flow" action with a drop down to select the contact field or flow, when you make a selection, the drop down switches to "Loading.." momentarily before switching to the selected field. What's going on there?

**Comment by ycleptkellan** [comment]
the select control we're using makes a network request on each selection and that's the default loading placeholder. agreed it looks weird; does removing that placeholder help a bit?

https://deploy-preview-210--hardcore-hypatia-8b3d76.netlify.com/

**Comment by ericnewcomer** [comment]
An alternative would be setting the loading placeholder to the same as help text. This is assuming we are satisfied with the spinner providing the loading feedback (I think I am).

**Comment by ycleptkellan** [comment]
i'm ok w/ that

**Comment by ycleptkellan** [comment]
(the loader being the only feedback.) i think fetching on each selection is a bit aggressive anyways; are going to want to cache those ourselves at some point?

**Comment by ericnewcomer** [comment]
Oops, I misunderstood the initial concern. Seems we ought to be able to avoid the refetch here on select if that is indeed what is happening.

**Comment by ycleptkellan** [comment]
addressing this in #216, didn't realize we were explicitly setting the `cache` prop to `false` 😅
