### ISSUE TITLE
Canvas Zoom

### ISSUE THREAD

**Issue by ycleptkellan** [nyaruka/floweditor#233]
Issue to document our thoughts on adding the ability to zoom the canvas and how we'd like to see it implemented. 

Initial notes:

- jsplumb [provides a widget for zooming](https://jsplumbtoolkit.com/docs/toolkit/widget-surface.html#pan-nudge-bars) that relies on mouse wheel/pinch events
- zooming could also be handled by a clickable canvas-management widget, e.g. [something like this](https://monosnap.com/file/p2erv7BahbAcIjTTimy7SpFjnmgYGI)

**Comment by ycleptkellan** [comment]
@ericnewcomer looks like we'll want the toolkit edition of jsPlumb if we want mouse wheel/trackpad zooming out of the box. What are your thoughts? Worth it?

**Comment by ericnewcomer** [comment]
Only concern there is how licensing something might impact our bundling options. Just adds a new element of consideration to make sure we are honoring any restrictions there.

My gut is that we can build our own here using the setZoom hook that we control completely and fully understand / own.

**Comment by ycleptkellan** [comment]
OK, makes sense. Any strong feelings on the team as to how zooming should be initiated, e.g. hooking into the mouse wheel event or adding a zoom widget?

**Comment by ericnewcomer** [comment]
I feel like mouse-wheel still doing a vertical scroll would feel the most natural to users (and I think we still want to encourage vertically expanding flows). I also feel that supporting zoom is only a means to ease canvas panning, which we can implement without zoom. So might make sense to start there.

**Comment by ycleptkellan** [comment]
@ericnewcomer Thanks will do. 

@rowanseymour Will def look into that 👍
