### ISSUE TITLE
SetContactAttrib should prune whitespace

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/floweditor#250]
Both when creating a new field and checking for reserved names.

**Comment by ycleptkellan** [comment]
Looked into this a bit and it looks like we’ll need to make use of the ‘isOptionUnique’ callback react-select provides. It’ll give us the option-to-be and any existing options that might match. It might also be a better place to compare the new option with our static list of contact properties than the ‘isValidNewOption’ callback.
