### ISSUE TITLE
Asset Service

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/floweditor#279]
We need a service inside the editor that can facilitate directing asset requests locally or to an external asset server transparently.

As a result of a discussion today, we've determined that we want to create groups and fields at the point they are made in the editor (so as part of modal validation where they are created, ie, add group, update contact). This is primarily so we can deal with validation issues with group creation (are they over the group limit, etc). To facilitate this, we need to modify the asset server spec to deal with object creation and hand back errors if it fails that can be surfaced in the modals.

Instead of standing up an http-based asset server for standalone editing, we should investigate having a service that has awareness as to its mode (standalone or integrated) and behave accordingly by either storing and fetching things locally or relaying on to http endpoints. 

_Implementation thought:
Hopefully this can be integrated inside the `SelectSearch` element by leveraging local options with no AJAX endpoint for the standalone case._

**Comment by ycleptkellan** [comment]
Sweet, in the local case would the idea be to leverage browser storage? If so, [localForage](https://github.com/localForage/localForage) might be a consideration.

**Comment by ericnewcomer** [comment]
Not sure it's necessary for this since the local case should never have a lot of data for the asset service, so just whatever in redux is probably fine. But could definitely see us looking to browser storage at some point if we decide there is value there.

**Comment by ycleptkellan** [comment]
That would be pretty cool!
