### ISSUE TITLE
Validate contact.fields expressions exist

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/floweditor#450]

**Comment by rowanseymour** [comment]
Looks like old code just regexes in templates for things that look like contact field references. That's probably safe for now in the new editor but we could do it more robustly in the future by finishing https://github.com/nyaruka/tsexcellent

**Comment by ericnewcomer** [comment]
Ya, pretty sure I implemented that rather quickly in the old one and will do the same here. Totally agree a full parse would be far better for a lot of different reasons.

**Comment by ericnewcomer** [comment]
Addressed in #481
