### ISSUE TITLE
Be more forgiving for missing _ui

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/floweditor#598]

**Comment by jlev** [comment]
I think I'm seeing an issue related to this. I've exported some new flows from TextIt.in to a local installation. Some work, and some don't render. Getting this error:

```Uncaught (in promise) TypeError: Cannot read property 'type' of undefined
    at rl (helpers.ts:473)
    at thunks.ts:257
    at index.js:12
    at dispatch (applyMiddleware.js:46)
    at thunks.ts:318
    at l (runtime.js:45)
    at Generator._invoke (runtime.js:264)
    at Generator.e.<computed> [as next] (runtime.js:98)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
```

Still trying to track down exactly what's happening, but if ui were undefined that would certainly be a problem here https://github.com/nyaruka/floweditor/blob/master/src/store/helpers.ts#L473

**Comment by nicpottier** [comment]
Export of new flows wasn't supported until we merged: 
  https://github.com/nyaruka/rapidpro/pull/2409

There are still some edge cases at that. None of this stuff is quite ready for outside consumption yet which is why we haven't merged upstream.

**Comment by nicpottier** [comment]
Oops, didn't mean to close Eric's todo. :)
