### ISSUE TITLE
Error __flow_editor_config__ is not defined

### ISSUE THREAD

**Issue by jnoliver2** [nyaruka/floweditor#60]
Im new to react. I tried setting this up locally but i get the error  __flow_editor_config__ is not defined

seems like its not picking these from the global.d.ts

app.tsx:2 Uncaught ReferenceError: __flow_editor_config__ is not defined
    at Object.<anonymous> (app.tsx:2)
    at __webpack_require__ (bootstrap 85ce29f4cf717d89a10a:19)
    at Object.<anonymous> (floweditor.js:84974)
    at __webpack_require__ (bootstrap 85ce29f4cf717d89a10a:19)
    at module.exports (bootstrap 85ce29f4cf717d89a10a:65)
    at bootstrap 85ce29f4cf717d89a10a:65

**Comment by jobala** [comment]
I am having the same issue as well,

It doesn't look like a react issue though.

How/where do we` define the flow_editor_config` ?

**Comment by ericnewcomer** [comment]
Currently it's not really configured for standalone development, though we'll get it back there in time. It's meant to be run from an external container, specifically our reference implementation, flowbase.

https://github.com/nyaruka/flowbase

**Comment by jnoliver2** [comment]
Thanks, Eric.
I'm getting a 404 on https://github.com/nyaruka/flowbase

Seems like it's not open public.

**Comment by ericnewcomer** [comment]
You just need to configure it from the containing page. Try something akin to this (with your own endpoints of course).

```
    var __flow_editor_config__ = {
      flow:"{{object.uuid}}",
      path: "{{STATIC_URL}}flow-editor/dist/",
      languages: { "eng": "English", "spa": "Spanish", "fre": "French"},
      endpoints: {
        fields:"/api/v1/fields.json",
        groups:"/api/v1/groups.json",
        flows:"/api/v1/flows.json",
        activity:"/api/v1/flow_activity.json",
        engine:"/fs/"
      }
    };
```

This all might be an exercise in frustration as the api for those endpoints is not documented, so you'd have to inspect the code. At some point, we'll get back to easier local development, but right now we are focused on bringing http://github.com/rapidpro/rapidpro forward so it can run nextgen flows. Once we have that, we'll be able to complete the new editor.

**Comment by ericnewcomer** [comment]
We now have an functional standalone dev environment, closing this.
