### ISSUE TITLE
Check for contact phone number is failing when number is present

### ISSUE THREAD

**Issue by putorti** [nyaruka/floweditor#608]
This doesn't seem right. My contact does indeed have a phone number, but is failing a check in the new editor for it.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/82857/58903303-0e70b680-86d3-11e9-8af5-5c5a98a6be88.png">

![image](https://user-images.githubusercontent.com/82857/58903233-dd908180-86d2-11e9-9468-37fdfca0ef88.png)

**Comment by rowanseymour** [comment]
I assumed this was an engine error at first but seems editor uses wrong operand

**Comment by putorti** [comment]
Sorry I meant editor, my mistake. This same logic works fine in the old system.
