### ISSUE TITLE
Not obvious how to save as new result name

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#610]
You can type over an existing result name to enter a new result name, it's just not obvious. Maybe needs hint or something.

<img width="635" alt="Captura de Pantalla 2019-06-04 a la(s) 13 54 43" src="https://user-images.githubusercontent.com/675558/58905852-58a46880-86d0-11e9-8ece-a9eb16432c03.png">

<img width="636" alt="Captura de Pantalla 2019-06-04 a la(s) 13 55 25" src="https://user-images.githubusercontent.com/675558/58905892-6c4fcf00-86d0-11e9-91aa-81777d811555.png">

**Comment by putorti** [comment]
I almost filed this, someone probably got the email, but I eventually realized how it works since that's how the old contact field system works too. It's not intuitive that you can type in a dropdown. Low priority though since the functionality works!

**Comment by rowanseymour** [comment]
Yeah I saw your comment via email, tried it, thought it was impossible, then realized it works, then saw your comment was gone!

**Comment by ericnewcomer** [comment]
This originally wasn't a dropdown, but we added it for convenience/consistency when editing flows.

How about..

* No default result selected
* Placeholder text "Enter the name to create a new result"

**Comment by rowanseymour** [comment]
That sounds like it would work. Do we have any other examples of a select-one-or-add-new control?

**Comment by ericnewcomer** [comment]
It's how Add to Groups works. That one just says "Select Groups" but it's possible people don't realize they can create them on the fly. Updating contact fields, same thing. That one is a bit different too because it also has non-field options in the drop down.

**Comment by rowanseymour** [comment]
Yeah I think it needs similar tweaking so maybe the placeholder text disappears when you're ready to type something. Right now the caret just appears over the placeholder, i.e.

<img width="163" alt="Captura de Pantalla 2019-06-05 a la(s) 11 11 18" src="https://user-images.githubusercontent.com/675558/58972252-bc876980-8782-11e9-967e-72b9c267783a.png">
