### ISSUE TITLE
Some flows are not selectable as an option for "Enter a Flow"

### ISSUE THREAD

**Issue by chris-erickson** [nyaruka/floweditor#611]
We have a flow that isn't particularly old (not older than some in the list) but it doesn't appear as an option in "Enter a Flow".  The one we're missing is "Verify Title" - it's not in the list, but I can see the flow otherwise (ie. can browse to and edit it normally).  It was suggested that maybe this is the wrong flow type and we should "start someone else in a flow" but use the same user.  It's not an option there either.

![image](https://user-images.githubusercontent.com/3322287/58908037-21848600-86d5-11e9-98cd-9d0a43214e61.png)

**Comment by ericnewcomer** [comment]
@chris-erickson tried to find this on your server, but no longer have access. Can you share an example of what your flows endpoint is returning (just have a look at XHR requests after opening this dialog).

**Comment by ericnewcomer** [comment]
Actually, I think I know what the issue is. What if you search for `Verify`

**Comment by chris-erickson** [comment]
Did you still need to see that?  It's a pretty extensive json, but I don't see the missing flow there (no errors or anything either).  Looks like maybe it's in a `results` element of another flow, but not as a primary element in the top-level `results`.

Based on your fix, looks like maybe we just weren't seeing the next page of results, and probably getting them sorted by something vaguely creation date related?

**Comment by nicpottier** [comment]
Yep, that's most certainly it.

**Comment by chris-erickson** [comment]
Verified Fixed ✅🎉
