### ISSUE TITLE
Expressions that return empty/null are crashing simulator

### ISSUE THREAD

**Issue by putorti** [nyaruka/floweditor#612]
I migrated some expressions we use to handle user stats from old to new flow engine:

`@(if(fields.letters_sent_today <> "", fields.letters_sent_today, 0) + run.results.messenger.extra.num_messages_sent)`

`@(if(fields.total_letters_sent <> "", fields.total_letters_sent, 0) + run.results.messenger.extra.num_messages_sent)`

Basically just trying to set a possible empty value to zero. Did the `<>` operator change? I guess I could set these values to 0 if empty with more complex steps beforehand.

Anyway, when trying to diagnose/fix these, I put them in their own flow. Running them in simulator just crashed simulator. It seems reproducible with other expressions that return blank output.

This will also crash simulator and then remove the step from the UI until you reload the page.

<img width="392" alt="image" src="https://user-images.githubusercontent.com/82857/58911459-d32bb300-86e5-11e9-9c00-f4bf7f95c500.png">

**Comment by rowanseymour** [comment]
`<>` should be `!=`. We're soon going to add the ability to convert existing flows to the new world and we have code to automatically migrate expressions. We also hope to put some documentation together soon to help users with the new expression syntax

In the meantime.. I guess it might be helpful to look at 
https://github.com/nyaruka/goflow/blob/master/legacy/expressions/migrate_test.go

There's also a bug we just fixed (#602) causing simulator to blow up when flow ends with a send message action.. you might be running into that.

**Comment by ericnewcomer** [comment]
Pretty sure this is running into #602. If you extend that flow to a wait and it still blows up at the first step, feel free to reopen.
