### ISSUE TITLE
Some UI language questions

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/floweditor#620]
The language here should address these goals:
1. Follow a common pattern, leading with the verb
2. Complete the sentence, "When a contact arrives at this point in your flow..." but still be able to stand on its own.
3. Have sufficient keywords for searching
4. Be a consistent tense and voice 

First let's establish what we have today. I've bolded the parts I'm not particularly wild about.

When a contact arrives at this point in your flow...
- Send **the contact** a message
- Wait for **the contact** to respond
- Send **somebody else** a message
- Label the incoming message
- Add **a URN** for the contact
- Add **the contact** to a group
- Remove **the contact** from a group
- Send an email
- Save a result **for this flow**
- Call a webhook
- Call Zapier
- **Enter another flow**
- Start somebody else in a flow
- Send **the contact** airtime
- Split by a custom expression
- Split by a contact field
- Split by a result in the flow
- Split by random **chance**
- Split by group membership

IVR
- Play a message
- Wait for menu selection
- Wait for **multiple digits**
- Play **a contact recording**

Surveyor
- Wait for an audio **recording**
- Wait for an image
- Wait for a video
- Wait for location **GPS coordinates**

**Comment by ericnewcomer** [comment]
Another thing to think about is we are starting to conflate the meaning of rulesets and actionsets to users and the distinction isn't super helpful to them I don't think. I'd like to see us move toward calling all of these options an action for the user in our support and knowledgebase, ie, _use the "Split by custom expression" action..._

**Comment by nicpottier** [comment]
I don't feel any of these are terribly bad. Why don't you like *contact* in a lot of these? I feel like things like *contact* and *URN* while somewhat technical is useful vocabulary for users to learn, it allows much more precise language else where.

Agree that actionset and ruleset aren't super useful. Not positive how I feel about us using the term action for a split though. You don't think those have different meanings to users? I suppose the confusing ones are the fancier ones such as webhooks or even normal waits. Those feel different than splits as well.

That said, especially as they are in the same drop down now I think I'm ok with trying on "action" for size and seeing how that works out.

**Comment by rowanseymour** [comment]
I have to admit I didn't realise I could type to search for actions/splits and have found it awkward to find particular things in that list. Guess a video about the new editor would help users discover stuff like that! Or.. a little icon by each option might help users looking through that list.

I don't hate any of the terminology currently used... or at least I'm struggling to think of better options.

**Comment by ericnewcomer** [comment]
The only reason contact is bold is because it feels awkward repeated..
When a contact arrives at this point in your flow... Send the contact a message

Okay then, will just leave these as is if there aren't any better ideas.
