### ISSUE TITLE
Relax validation of HTTP header names to match engine

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#632]
See https://github.com/nyaruka/goflow/pull/700

**Comment by ericnewcomer** [comment]
@rowanseymour do you have an example that fails validation? We use an external validator for urls.
https://github.com/nyaruka/floweditor/blob/master/src/store/validators.ts#L12

**Comment by rowanseymour** [comment]
so that's using this for headers right?

```
export const HeaderName = fromRegex(/^[\w-]+$/, 'is invalid');
```

according to https://godoc.org/golang.org/x/net/http/httpguts#ValidHeaderFieldName, that's too strict. We have headers with periods in prod that I think we need to allow

**Comment by ericnewcomer** [comment]
Totally missed that this was for header names and not urls.
