### ISSUE TITLE
Incorporate Storybook.js

### ISSUE THREAD

**Issue by ycleptkellan** [nyaruka/floweditor#64]
Whereas [Jest](https://facebook.github.io/jest/) & [Enzyme](http://airbnb.io/enzyme/) allow one to comfortably _test_ components in isolation, [StoryBook](https://storybook.js.org/) allows for _developing_ components in isolation. It also allows for [rich documentation](https://atlaskit.atlassian.com/components/avatar).

**Comment by ycleptkellan** [comment]
[Quickstart](https://medium.com/@mtiller/storybook-react-typescript-and-jest-c9059ea06fa7)

**Comment by ycleptkellan** [comment]
[Storyshots](https://github.com/storybooks/storybook/tree/master/addons/storyshots) might also be useful (a form of visual regression testing)

**Comment by ericnewcomer** [comment]
Broken with with webpack 4. Perhaps revisit in the future.
