### ISSUE TITLE
Update auto-completion to reflect recent results context changes

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#642]
As of https://github.com/nyaruka/goflow/pull/708 `@results`, `@run.results`, `@child.results`, `@child.run.results`, `@parent.results`, `@parent.run.results` all have the same schema:

```go
return map[string]types.XValue{
  "__default__":          types.NewXText(r.Value),
  "name":                 types.NewXText(r.Name),
  "value":                types.NewXText(r.Value),
  "values":               types.NewXArray(types.NewXText(r.Value)),
  "category":             types.NewXText(r.Category),
  "categories":           types.NewXArray(types.NewXText(r.Category)),
  "category_localized":   types.NewXText(categoryLocalized),
  "categories_localized": types.NewXArray(types.NewXText(categoryLocalized)),
  "input":                types.NewXText(r.Input),
  "extra":                types.JSONToXValue(r.Extra),
  "node_uuid":            types.NewXText(string(r.NodeUUID)),
  "created_on":           types.NewXDateTime(r.CreatedOn),
}
```

**Comment by rowanseymour** [comment]
I think my vote would be omitting the plurals from auto-complete for now and introducing them when we introduce a new feature that uses them. That way we can blog/video about what they mean. For now they can only cause confusion.

**Comment by nicpottier** [comment]
Ya, agreed. There's no way to ever get anything with multiple values right now anyways.

**Comment by ericnewcomer** [comment]
So, just to be clear, if we are leaving off plurals, I don't think there is actually anything to change here.

<img width="283" alt="Screen Shot 2019-06-21 at 1 41 29 PM" src="https://user-images.githubusercontent.com/211652/59950274-50675f80-942a-11e9-9677-a1b80ff68e84.png">

**Comment by rowanseymour** [comment]
That looks right for `@results` but we want same schema for `@run.results`, `@child.results`, `@child.run.results`, `@parent.results`, `@parent.run.results`

<img width="283" alt="Captura de Pantalla 2019-06-21 a la(s) 15 44 05" src="https://user-images.githubusercontent.com/675558/59950435-88c36980-943b-11e9-8bee-23b8b89db06d.png">

**Comment by rowanseymour** [comment]
Side note, should description for `@result.foo` indicate that it is equivalent to `@result.foo.value`? @nicpottier was lamenting this morning that users don't appear to be using `@result.foo`. I know I personally tend toward the most explicit leaf cuz I usually can't remember what a branch defaults to.

**Comment by ericnewcomer** [comment]
Can do that, one thing to point out is that there isn't anything to change for @child and @parent since we don't currently surface results for those yet.

Will audit @results and @run.results to make sure they match and will update the description for the default value.

**Comment by rowanseymour** [comment]
Re parents and children - just making sure you've seen https://github.com/nyaruka/goflow/issues/703 which wouldn't be for v5.0
