### ISSUE TITLE
Update language action should use language name, not code

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#646]
A bit weird as it seems to know the language name in the drop down when I first set it, but when displayed in the overview and when reentering the edit it just shows the code.

<img width="118" alt="Test Flow 2019-06-21 10-44-58" src="https://user-images.githubusercontent.com/168067/59934723-d3c88700-9411-11e9-9ac5-71f5092513fd.png">
<img width="332" alt="Test Flow 2019-06-21 10-45-15" src="https://user-images.githubusercontent.com/168067/59934729-d6c37780-9411-11e9-9582-ea5a6d4a7fde.png">

**Comment by ericnewcomer** [comment]
This is because the definition doesn't store it and the editor only knows about languages set on the org, so not enough information to show that. 

Choices here are:
1) Embed the language name with the code
2) Add a lookup endpoint to resolve language names

**Comment by nicpottier** [comment]
But it shows it in the first drop down? Confused what the difference is there.

**Comment by ericnewcomer** [comment]
That is pulled from the org. So using that wouldn't work for imported flows with different languages.

**Comment by nicpottier** [comment]
Ok. Maybe I'm misunderstanding something here. Do you disagree that it would be nicer to have the language name (not code) when that language IS present on the org? That seems like the 99% case. Back down to the code if not present otherwise?

**Comment by ericnewcomer** [comment]
No, not at all, I think we should definitely have the name. I punted on it because hadn't settled on 1 or 2 above. I do think that to implement it we should support non-org languages.

**Comment by ericnewcomer** [comment]
Language names themselves should at some point be shown in the local language, so that is one argument for 2.
