### ISSUE TITLE
Trigger flow doesn't support creating new contact

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#658]
"Start somebody else in a flow" needs to support the use case of people creating brand new contacts. This is currently an attribute on the action named `create_contact` which should be set to `true`.

**Comment by rowanseymour** [comment]
this for 5.0? it's not a commonly used feature but we have totally broken it.. so thinking yes

**Comment by nicpottier** [comment]
Ya, I'm of two minds, it does seem sucky to say that even in Beta form it is broken for cases that involve starting new contacts. That said, we probably will find other breaking items in the future and we aren't going to backport those to 5.0 I don't think. So maybe this just falls into a release note and this just comes with using a BETA editor?

**Comment by rowanseymour** [comment]
I can live with that
