### ISSUE TITLE
Quick replies don't appear when translating

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#660]
Repro:
 1. Create flow in multi language org
 2. Create step with quick replies in base language
 3. Flip to translation, quick replies don't appear in overview mode (they should in the default language in yellow I think as we will send them that way) and in the detail tab for that reply there are no quick replies / translation treatment.

**Comment by ericnewcomer** [comment]
@nicpottier can you add a screenshot for this? I'm trying to repro and not sure I'm looking at the same thing.

**Comment by nicpottier** [comment]
Hrmm. I think maybe repro is actually slightly weirder.. You first create the quick replies in the base language, then switch language, then click on the node, then click on quick replies tab. If you press "ok" then the quick replies are cleared and there's no way to get back to the base quick replies.

Maybe that's expected? Even if I add a quick reply in my translated language it doesn't appear on the node. They aren't really treated in the same kind of "translation" way that everything else is. (where you see the base version and you are providing translations)

![Screen Shot 2019-07-05 at 7 00 39 AM](https://user-images.githubusercontent.com/168067/60727397-a213ed80-9ef2-11e9-8f01-7beb5ac319ef.png)
![Screen Shot 2019-07-05 at 7 00 35 AM](https://user-images.githubusercontent.com/168067/60727398-a2ac8400-9ef2-11e9-99ed-a36153769966.png)

**Comment by ericnewcomer** [comment]
Shoot. There must be something else slightly different. When I add quick replies in a second language they do show in the overview just like the localized text.

**Comment by nicpottier** [comment]
https://textit.in/flow/editor_next/bb89fb44-da0c-4a9b-9f29-d5e07600e663/

**Comment by ericnewcomer** [comment]
Oh oh. I think maybe I was misunderstanding? The concern is the base quick replies don’t show for non localized quick replies?

**Comment by nicpottier** [comment]
They do initially, then as soon as you click into the node then they disappear. I'm guessing we are setting them to empty at that point?

**Comment by ericnewcomer** [comment]
Sounds like it, will have a look. This helps, thanks!
