### ISSUE TITLE
Completion URNs need to be in sync with goflow

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/floweditor#672]
See https://github.com/nyaruka/gocommon/blob/master/urns/urns.go#L13

**Comment by ericnewcomer** [comment]
Could perhaps prioritize this behind #650

**Comment by rowanseymour** [comment]
Would imagine #650 could take a while to get out there, no?

**Comment by ericnewcomer** [comment]
Once there's an endpoint in mailroom, don't see why it would take more than a day or so to incorporate it here.

**Comment by rowanseymour** [comment]
I just mean you could fix this in a few minutes, and it seems we're still discussing #650

**Comment by ericnewcomer** [comment]
https://github.com/nyaruka/floweditor/pull/678
