### ISSUE TITLE
Split by phone number using formatted number

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#676]
If using "Split by Contact Field" -> "Phone Number" the operand built is `@(format_urn(urns.tel))` instead of what I would expect `@(urn_parts(urns.tel).path)`

Old behavior was to have the entire path there, so people have rules that look like:
![Screen Shot 2019-07-16 at 6 44 11 AM](https://user-images.githubusercontent.com/168067/61299565-2c7f0b80-a795-11e9-9486-19ce4d867693.png)

That doesn't work because we are actually splitting on something more like `07 9604 8434` right now. Given that formatting of numbers can change and that it isn't super predictable how they will look to users, and that we are losing country code information when doing so, I think we should be splitting by path instead.

@rowanseymour what are we migrating as? Customer said their previous split turned into a "Split by Contact" -> "Name" but I wonder if we are migrating to some other expression and then defaulting our display to "Name" because the editor doesn't understand it.

**Comment by rowanseymour** [comment]
In the legacy editor, if you pick the "Phone Number" field, that sets the operand to `@contact.tel_e164` (note, not `@contact.tel`) and if you migrate that, you get `@(urn_parts(urns.tel).path)`.

However if you set it to a different scheme type, say Twitter, the operand will be `@contact.twitter` and that will migrate to `@(format_urn(urns.twitter))`

There's no special, logic for migrating these rulesets - that's just what those expressions migrate to.

Seems like it new editor could use `@(urn_parts(urns.<SCHEME>).path)` for all schemes moving forward?

**Comment by nicpottier** [comment]
To be clear, I was just positing that maybe the editor is defaulting the UI to be "Split by Contact"->"Name" when it sees a def that has a split by contact it doesn't understand.

The weird cases are things like telegram, where path may be something like `1235512415` and display is something like `nicpottier` (which would appear for a `format`). I'm not sure it is entirely clear which the user would expect / which is right. I think it would generally feel to me that the latter would be more expected, since the use of ids is mostly transparent to users, which is an argument towards `format` for non-tel?

**Comment by ericnewcomer** [comment]
Will look but suspect @nicpottier is correct. The split by phone would be a UI type so perhaps it’s not set on migration.

**Comment by rowanseymour** [comment]
Frankly it's hard to imagine a real use case for splitting on schemes besides tel because.. tel URNs are somewhat unique in that you can derive information from the path. So can't say I feel strongly about how other schemes should split. Users can always explicitly choose formatted vs non-formatted in a regular Split By Expression. Only argument for treating other schemes the same is consistency.

**Comment by ericnewcomer** [comment]
To be clear I don’t believe we’ve ever offered splitting on other types of urns as a first class thing. I think it’s always required a split by expression. Don’t see a strong reason to change that right now.

**Comment by rowanseymour** [comment]
Are we talking about same thing.. 

<img width="674" alt="Captura de Pantalla 2019-07-16 a la(s) 10 18 04" src="https://user-images.githubusercontent.com/675558/61306937-049ea080-a7b3-11e9-847a-811fd681df33.png">

**Comment by ericnewcomer** [comment]
Gah, brain phart. Yes, had that totally wrong in my head.

**Comment by nicpottier** [comment]
Agreed that it doesn't seem like a common thing for any other scheme. Do we even have flows that split by any other scheme? Maybe we should just add `URN` to the split by for the general case (and use `format`?) and remove all other other options apart from Phone Number? 

PS: for consideration can we change "Phone Number" to "Telephone Number" just because I tried searching for "tel" in our dropdown and didn't find it?

**Comment by nicpottier** [comment]
Or maybe to be more specific the option would be `Formatted URN`?

**Comment by rowanseymour** [comment]
I would guess the most common non-tel way of using this would be just an existence check, e.g. does this user have a Whatsapp URN? So it doesn't matter so much how the URN becomes the operand, but it does require letting users select each URN scheme.

(wish we had better way to search thru flow defs and answer questions like this..)

**Comment by nicpottier** [comment]
Oh good catch, I think that's exactly right.

Ok with that additional detail I think I'm fine always using path regardless of scheme, since that is the most accurate thing for that kind of test anyways. (and the only one I can think of that even makes sense)

As you said, for anything more advanced they can use split by expression.

**Comment by ericnewcomer** [comment]
Just to show what's happening today..

On migration we get:

Phone: 
`@(urn_parts(urns.tel).path)`
```
"config": {
  "operand": {
      "id": "tel_e164",
      "type": "field"
   }
}
```

Others: 
`@(format_urn(urns.telegram))`
```
"config": {
  "operand": {
    "id": "telegram",
    "type": "scheme"
  }
}
```

Using the editor we get something like this for all urns:
```
@(format_urn(urns.tel))

"config": {
  "operand": {
    "id": "tel",
    "type": "scheme",
    "name": "Phone Number"
  },
  "cases": {}
}
```

**Comment by nicpottier** [comment]
Oh funny, so we were already using `format_urn` for the non-tel cases.

Heh, well, maybe we just stick to that and just update editor? Technically any other change would require a migration or at least editor support for showing things it doesn't understand.

**Comment by ericnewcomer** [comment]
Well technically, we need to change the goflow migration since it's missing the config to present these properly to the user. Question is do we fix existing migrated flows or not.

Also, to make sure I understand, for the editor change, the recommendation here is to add a special case for tel urns to use `@(urn_parts(urns.tel).path)` instead of `@(format_urn(urns.tel))`

**Comment by nicpottier** [comment]
> Well technically, we need to change the goflow migration since it's missing the config to present these properly to the user. Question is do we fix existing migrated flows or not.

Right, though only applies to old flows that have opted in to new editor and use this type of split. I guess alternative would be for the editor to handle the "don't understand this" case as a split by expression which would at least make the old migrations look correct.

> Also, to make sure I understand, for the editor change, the recommendation here is to add a special case for tel urns to use @(urn_parts(urns.tel).path) instead of @(format_urn(urns.tel))

Yes, I think that's right. Though I could very easily be convinced that we should just use `@(urn_parts(urns.tel).path)` all the time.

**Comment by ericnewcomer** [comment]
I could also very easily be convinced against special cases! ;)

**Comment by rowanseymour** [comment]
Ok since everyone is "easily convinced".. I think I'd lean toward `@(urn_parts(urns.<scheme>).path)` for all

**Comment by nicpottier** [comment]
Ok, then the fix is have editor to use that for everything but then also to have editor gracefully backdown to expressions it doesn't understand in split by contact?

**Comment by ericnewcomer** [comment]
Ya, noodling on the back down part. Feels a little weird to have the editor effectively do a migration. Will come up with something for that.
