### ISSUE TITLE
Missing map's validation on

### ISSUE THREAD

**Issue by WilliamTales** [nyaruka/floweditor#683]
# Description

Categorizing options for "has a state" or "has a district" not working on new flow's editor version.

# Details

Once you create an old flow's version and convert it will be displayed in red:
![image](https://user-images.githubusercontent.com/35577716/62233073-25afe580-b39e-11e9-916b-b16faadb3927.png)

On the new flow's version (native or converted) these options are not listed:
![image](https://user-images.githubusercontent.com/35577716/62233388-dddd8e00-b39e-11e9-8159-f9f8a7db57a7.png)

# Expectations

Is this feature going to be covered and it's being developed? How can we contribute to its development?

**Comment by ericnewcomer** [comment]
Will have a look. If this is missing it’s an oversight. Thanks!

**Comment by WilliamTales** [comment]
Thx @ericnewcomer highly appreciated.
