### ISSUE TITLE
'Run Code' action

### ISSUE THREAD

**Issue by ycleptkellan** [nyaruka/floweditor#70]
Useful in situations where a 'Split by Expression' RuleSet/custom expression wouldn't be enough and a 'Call Webhook' action would be overkill. 

Some examples from other platforms: 
- [FlowXO](https://support.flowxo.com/article/145-code )
- [Zapier](https://zapier.com/help/code/)

**Comment by ycleptkellan** [comment]
Twilio's rip-off editor has a similar concept: https://www.twilio.com/docs/api/studio#run-function

**Comment by ericnewcomer** [comment]
For consideration on goflow
