### ISSUE TITLE
Delimited field split should use zero-based index

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#701]
If you pick first item, generated operand is...

```
@(field(results.resp1, 1, \".\"))
```

**Comment by ericnewcomer** [comment]
I swear excellent was one-based for these at some point. Maybe that was the old excellent? Will change.

**Comment by rowanseymour** [comment]
Excellent 1.0 aka Classic Edition was always 1-based like Excel

**Comment by ericnewcomer** [comment]
Classic Edition or Excellent 2017?
