### ISSUE TITLE
Editor crashes if you try to enter an expression when setting language

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#708]
<img width="255" alt="Captura de Pantalla 2019-09-27 a la(s) 11 35 25" src="https://user-images.githubusercontent.com/675558/65785906-14bfee00-e11b-11e9-9ebd-365aa781440d.png">

Soon as I type `@` the modal and flow both disappear..

<img width="534" alt="Captura de Pantalla 2019-09-27 a la(s) 11 35 56" src="https://user-images.githubusercontent.com/675558/65785908-17224800-e11b-11e9-841f-6a5af590977b.png">

**Comment by ericnewcomer** [comment]
Anytime it blows up it's a bug, but we've never actually supported expressions here. This has always just been a drop down of languages.

**Comment by rowanseymour** [comment]
Hmm yeah I wasn't sure about that - engine considers them to be expressions...
