### ISSUE TITLE
Connector left in weird state when new action automatically becomes new node

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#711]
<img width="310" alt="Captura de Pantalla 2019-09-27 a la(s) 11 53 15" src="https://user-images.githubusercontent.com/675558/65792607-bcdcb380-e129-11e9-8498-5675cf1d0137.png">

**Comment by rowanseymour** [comment]
I guess this is because it's the initial node and it just needs to know to hide the tooltip thing once the new node has been created

**Comment by ericnewcomer** [comment]
Yup, that's correct, will fix.
