### ISSUE TITLE
Autocomplete for child results uses result names from current flow

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#712]
Seems like this should just not autocomplete past `@child.results` which appears to be the case for `@parent.results`

<img width="666" alt="Captura de Pantalla 2019-09-27 a la(s) 13 27 01" src="https://user-images.githubusercontent.com/675558/65793019-92d7c100-e12a-11e9-80cd-e1528721bdf2.png">

**Comment by ericnewcomer** [comment]
Hmmm.. so this was introduced when we started doing completion based on http://textit.in/mr/docs/completion.json

Those look the same to the completion widget. Should we have some flag there?

**Comment by rowanseymour** [comment]
Ah good point the type of `run.results` is `results` but the type of `related_run.results` should just be a generic object as we can never know the properties. I'll update in goflow...

**Comment by rowanseymour** [comment]
So actually I don't think any changes are needed here - fixed in https://github.com/nyaruka/goflow/commit/1b7858e64ba91f19f07742337cb0fb64d9559e43
