### ISSUE TITLE
Validation error after removing nodes

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/floweditor#723]
There may be an even tighter repro, but this one works 100% of the time.

Repro steps:
1) Starting with an empty flow, create a single message
2) Drag to create a wait for response, add one category, save
3) Open wait node, remove extra category, save
4) Delete wait node

This will then fail validation as the destination from the first node is not cleared. Instead it is still pointing to the old deleted split node.

**Comment by putorti** [comment]
I'm not sure if this is helpful or related but I can reproduce this 100% of the time:

1. Copy valid/working flow that's using the new editor
2. Make any change on the new, copied flow
3. Get validation error on change, asking me to reload the page
4. Reloading loses all changes

We're still trying to figure out how to get the mailroom logs to figure out what's going on.

**Comment by ericnewcomer** [comment]
Hmm, doesn't repro for me, so your steps need to be narrowed more than that. Guessing the flow being cloned likely has something to do with it. One thought there is the remapping of uuids on the clone isn't producing a clean flow definition, so yours could very well be a bug in RP not in the flow editor. I would map out the repro steps starting from an empty flow with as few steps as possible, and file an issue on RP for that.

As for this ticket which evidently is unrelated, I simplified the repro further:

1) Starting with an empty flow, create a single message
2) Drag to create a wait for response
3) Open wait node, save
4) Delete wait node

**Comment by chris-erickson** [comment]
Sorry if I'm not helping, but in one of these flows that won't load for us, I get (one request fires after the other, when I click the Gear, then Edit):
<img width="846" alt="image" src="https://user-images.githubusercontent.com/3322287/67108165-8e378300-f193-11e9-846a-55c0097a99ce.png">
and
<img width="844" alt="image" src="https://user-images.githubusercontent.com/3322287/67108187-98f21800-f193-11e9-9115-030e3778157a.png">

If you have some specifics on what I might look for in logs, that could be helpful.. mailroom for us is set to debug which is.. noisy..

**Comment by ericnewcomer** [comment]
This issue is about a validation error trying to save not about a flow not loading. Sounds like this is meant for a different issue?

**Comment by chris-erickson** [comment]
Ok, removed that - can you point me to anything to help sifting through mailroom logs?  What text is in the message, or place in code where this happens?  I can see in the UI now that there's a 400 `POST`ing to `https://rapidbot.io/flow/revisions/46cabbef-a64c-4eea-b23b-b1dbc847a95d/` so I hope I'm on the right problem now..

**Comment by nicpottier** [comment]
This is almost certainly that that flow has references to either channels or other flows that don't exist, which would cause it to fail validation. You should be able to do something like this from a Python shell with the flow definition to get more details as to why it is failing (see flows/models.py for examples):
`flow_info = mailroom.get_client().flow_inspect(definition, validate_with_org=org)`

**Comment by putorti** [comment]
It doesn't though, again it's an exact duplicate of a working flow. I guess I need to start deleting steps one at a time, copying, seeing when it starts working.

<img width="921" alt="image" src="https://user-images.githubusercontent.com/82857/67111409-d90cc700-f1a2-11e9-9e28-f7617099bbbc.png">

If you guys want me to not talk about my issue here, okay; Eric shot me a note saying this seemed related.

**Comment by nicpottier** [comment]
Well then I'd be really curious to hear what the command above returns.

**Comment by chris-erickson** [comment]
Working through it, something with the groups, but the groups referenced do exist to the best of our knowledge (not the UUID in the flow definition though)
```
>>> mailroom.get_client().flow_inspect(f.get_definition(), validate_with_org=f.org)
DEBUG 2019-10-18 16:34:56,286 base 25799 139926827915008 Sending message of length 3307 to https://sentry.io/api/152161/store/
Traceback (most recent call last):
  File "/usr/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/home/rapidpro/releases/r5.0.9/temba/mailroom/client.py", line 63, in flow_inspect
    return self._request("flow/inspect", payload)
  File "/home/rapidpro/releases/r5.0.9/temba/mailroom/client.py", line 106, in _request
    raise FlowValidationException(endpoint, payload, resp_json)
temba.mailroom.client.FlowValidationException: flow failed validation: missing dependencies: group[uuid=1b13da60-28ec-4a8c-8776-dec2825f2b7e,name=],group[uuid=ddbda9f2-1199-44e9-8d5f-7182df0545c1,name=]
```

**Comment by rowanseymour** [comment]
@chris-erickson if that UUID doesn't map to any known group then I suspect the issue in that flow is something we ran into a while back (https://github.com/nyaruka/rapidpro/pull/2510) where the `has_group` doesn't import correctly - and you end up with a random UUID assigned to the group.. which then later when you try to edit the flow.. blows up at validation.

I'm afraid the only way to get out of that state is to manually change the group UUID in the definition. Goflow and the editor where also updated to allow the `has_group` test to store the name of the group which also avoids this problem.

**Comment by chris-erickson** [comment]
Got it, I guess we'll be deliberate about copying, and look forward to that next release 🎉

**Comment by ericnewcomer** [comment]
Just leaving a quick note to myself that the original issue here is something different and has not been addressed yet.

**Comment by ericnewcomer** [comment]
Original issue fixed in classifier PR here:
https://github.com/nyaruka/floweditor/pull/724/files#diff-9b0a3cb5ac9a481fbfc8bb6e32670b35R898
