### ISSUE TITLE
Simulator needs updating for new intent actions

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#727]
Seems we could show the webhook log the same as we do elsewhere. Perhaps we should also add some logging that is more friendly as well. (what the top intent was and its score?)

Do we want to show the setting of the _ result in simulation?

![Screen Shot 2019-10-22 at 7 36 15 AM](https://user-images.githubusercontent.com/168067/67297501-d9f17180-f49e-11e9-8751-566137b6142b.png)

**Comment by ericnewcomer** [comment]
Hmmm, this looks like a bug. I did make this work where it showed the http request.

**Comment by ericnewcomer** [comment]
Ya, this works locally but I was able to reproduce what you have there on staging. Maybe something changed and I need to update my local versions.

<img width="915" alt="Screen Shot 2019-10-22 at 10 51 24 AM" src="https://user-images.githubusercontent.com/211652/67314677-0070d600-f4ba-11e9-80df-7bf1fb48ae15.png">

**Comment by rowanseymour** [comment]
Oh this is probably where we moved the HTTP info to an array of `http_logs` on the event 😬

**Comment by ericnewcomer** [comment]
Ya, I'm rebuilding mailroom and definitely not up to date because it doesn't even compile without updating golang :)

By the sound of things, we probably broke all webhooks in the simulator with that. Looking into it.

**Comment by rowanseymour** [comment]
It was only a change to `classifier_called` and `airtime_transferred` actions

**Comment by ericnewcomer** [comment]
Fixed this to work with http log as an array. Also short circuiting result change events if they have intents / entities to show those _instead_. This means we don't show a reference to "_Result Classification" in the simulation log, not sure how much we want to surface that out of the gate.

<img width="269" alt="Screen Shot 2019-10-22 at 12 49 01 PM" src="https://user-images.githubusercontent.com/211652/67325658-58afd400-f4ca-11e9-91d3-e4ff8ad4dd32.png">

**Comment by nicpottier** [comment]
noice!

**Comment by ericnewcomer** [comment]
Maybe under that table we show something like..
Saved to @results._result_classification
