### ISSUE TITLE
Maybe should default confidence to 0.9?

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#728]
When first adding an intent case I think we should default the confidence to `0.9`. Most people aren't going to have a good idea what to put there anyways so lets not force them to type it out.

**Comment by rowanseymour** [comment]
Side note.. I can't remember which or find it now.. but I could swear one of the classifier APIs had an option to enable or disable normalization of confidences... which I took to mean having them add up to 1 regardless of absolute confidence. Am curious now how the confidences compare across different classifier types for similar models.

**Comment by rowanseymour** [comment]
Oh found it - it's a bothub setting...

<img width="538" alt="Captura de Pantalla 2019-10-22 a la(s) 10 18 33" src="https://user-images.githubusercontent.com/675558/67301702-660e9380-f4b5-11e9-9d8b-a045b44516da.png">

**Comment by ericnewcomer** [comment]
Made it a placeholder, but ya, I didn't have good enough confidence to make it a default. If you feel that number is an appropriate place to start, it works for me.
