### ISSUE TITLE
Odd styling on airtime transfer action

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#735]
Maybe. The new currency option just looks a little squashed... 

<img width="640" alt="Captura de Pantalla 2019-10-24 a la(s) 09 53 09" src="https://user-images.githubusercontent.com/675558/67497837-2c1fc780-f644-11e9-8a22-6734aca8a3af.png">

**Comment by ericnewcomer** [comment]
Fixed in #740
