### ISSUE TITLE
Completion Behavior for unknown items goofy

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#737]
When looking at items we don't know the contents of (say `@webhook` or `@results.foo.extra`) the completion behavior is a bit annoying.

When typing beyond the last thing it recognizes, it keeps the last "known" item up and pressing of enter or tab erases what you've typed and replaces it with that completion. Only way to make the completion go away is to add a space or the like.

Seems for those items that we know may have children we don't recognize we should hide the completion dropdown once you are beyond what we know about.

<img width="891" alt="Screen Shot 2019-10-25 at 8 01 40 AM" src="https://user-images.githubusercontent.com/168067/67582174-17076f00-f6fe-11e9-81ec-4600ace36e5c.png">

**Comment by ericnewcomer** [comment]
I've also encountered this recently accidentally writing over my variable. I agree that hiding in this case is the right thing.

**Comment by ericnewcomer** [comment]
Fixed in #815
