### ISSUE TITLE
Elevate SMS counter when it goes double byte

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#745]
This would probably be a pretty big win, especially for UNICEF offices that have relatively slow SMSC connections but very large number of U-Reporters.

We should do some things to more obviously call out that a message is being forced into UCS / UTF mode and highlight that. Right now we are still just using simple characters counting which doesn't take into account what is included in the GSM7 charset.

Could be as simple as correctly calculating the message parts count but then also show a little exclamation bubble that appears near that count if there is a non GSM7 character in the message and says why. (`Your message includes the characters "“" which will cause this message to be sent in multiple parts`)

This is probably one of the bigger wins we could make for our customers so maybe something for 5.4?

**Comment by rowanseymour** [comment]
Maybe useful too if simulator shows long messages as being split into smaller ones?

**Comment by nicpottier** [comment]
Well the handsets receive these as a single message, they are just turned into multipart, which can really slow things down.

Was just looking at a flow that sent two messages at the start of a flow and that turned into 8 physical parts across 1M contacts, so this is a big deal. (that totally backed them up for days)

**Comment by rowanseymour** [comment]
Fair point. Was trying to think of a way that users can see that expressions like `@contact` expand and gobble up more characters

**Comment by nicpottier** [comment]
Ah right, ya, that's totally a good point. Agree that showing number of parts there would likely be useful, maybe even something where you could click and see something like:
  https://www.textmagic.com/free-tools/sms-length-calculator

**Comment by ericnewcomer** [comment]
We should make it more overt, especially when the number of segments required doubles by adding an emoji. Also, there's some funny transparency there that needs to go.

<img width="265" alt="Screen Shot 2019-11-11 at 1 47 29 PM" src="https://user-images.githubusercontent.com/211652/68623767-173b9480-048a-11ea-94bb-e57e123c02d5.png">

**Comment by nicpottier** [comment]
Oh hah! Well then yes, just need to call that out more!

**Comment by nicpottier** [comment]
So ya, looked at this again for the poll I was worried about and the popup itself is pretty perfect. Maybe just a matter of calling it out more. Maybe a little `(!)` or something to the left when you use characters that are going to switch you to GSM mode and it is more than 1 message?

**Comment by ericnewcomer** [comment]
Ya, I don't see any reason we shouldn't make it super obvious in that case.

**Comment by nicpottier** [comment]
As we've done account reviews I've seen these more and more often. Wonder if we should make this an explicit warning you have to click through when closing the dialog if you have an SMS channel connected and the message is more than one segment and it has special characters. It has some pretty large consequences and we should be calling it out more.

**Comment by ericnewcomer** [comment]
This now animates to a larger font that is bolded and has a background when unicode characters are added. We can start here and perhaps move to a clickthrough next.
