### ISSUE TITLE
No warning on flow delete if flow is used in campaign

### ISSUE THREAD

**Issue by putorti** [nyaruka/floweditor#750]
Normally if you delete a flow that's used in another flow, you'll get a warning/block and a list of the flows where it's linked. If a flow is only used in a campaign, no such warning appears. Seems like that might be a good idea. I'm not sure what would happen if I just deleted the flow.

**Comment by ericnewcomer** [comment]
In this case, any campaign events that use that flow are removed along with it when it is deleted. If you'd like to open an issue to discuss changing this behavior, please open it on https://github.com/rapidpro/rapidpro.

Thanks!
