### ISSUE TITLE
Show more revisions in revision history

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#755]
Now that we are trimming revisions we should show more than the last 25.

For an idea of scale I think the biggest we've seen after trimming is ~140. But that trimming happens daily so an active flow author may get themselves with more than that in a specific day.

Maybe RapidPro should return a summarized revision history for that case? (hourly or something?)

**Comment by ericnewcomer** [comment]
Ya, I would agree that at this scale, seems we can remove the pruning of that list (which I'm pretty sure happens on rapid, so not sure we need to change anything on the editor).

**Comment by putorti** [comment]
Are revisions returning in the new editor? Also for an alternative idea, trimming by age rather than number could make sense. Summarized sounds nice.

**Comment by nicpottier** [comment]
They are visible sure, but they are still limited to most recent 25 which is what this issue is about.

**Comment by putorti** [comment]
<img width="216" alt="image" src="https://user-images.githubusercontent.com/82857/70569415-ecfff400-1b67-11ea-9c93-aec813a06168.png">

Apologies, where? Is this in a newer version? I haven't had access to revisions yet in the new editor.

**Comment by ericnewcomer** [comment]
The purple button in your screenshot

**Comment by ericnewcomer** [comment]
Fixed in #778
