### ISSUE TITLE
Populate global keys names in completion

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#756]
https://github.com/nyaruka/goflow/pull/806 will add a new type in completions.json called globals which then needs to be populated from the endpoint being added in https://github.com/nyaruka/rapidpro/pull/2615

```json
{
  "name": "globals",
  "key_source": "globals",
  "property_template": {
    "key": "{key}",
    "help": "the global value {key}",
    "type": "text"
  }
}
```

@ericnewcomer what happens if this appears in the completion before the editor is updated to handle it?

**Comment by ericnewcomer** [comment]
If it's not in the root I don't think anything.
