### ISSUE TITLE
Simulator can't send empty messages

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#762]
Would be useful for testing flows.

**Comment by rowanseymour** [comment]
Are empty messages a thing in the real world? Just concerned people will inevitably accidentally send empty messages from the simulator and end up worrying about a scenario that isn't going to happen in the real world. If it's only something we need for testing edge cases, could make it something like a long press on the Send button.

**Comment by nicpottier** [comment]
Are they possible? Sure, many channels can receive empty messages.

What's the worry of allowing people to click that when empty? Should be pretty obvious what happened there no? And if it doesn't fail validation that they have then all the more reason.

**Comment by WilliamTales** [comment]
Have you tried using @("") as the *Send Message* action?

**Comment by rowanseymour** [comment]
I honestly didn't think we ever dealt with empty messages... I don't think I've ever seen one. My only worry is making users think this is something to be expected. Maybe they start making flows that expect empty responses which isn't going to possible on most channels.

**Comment by nicpottier** [comment]
Empty messages are a thing. I know you don't want to believe me, but they do happen! Every SMS channel can get empty messages.

If we never thought they could happen we wouldn't have a "Has some text" rule would we?

**Comment by rowanseymour** [comment]
> we wouldn't have a "Has some text" rule would we?

That test trims whitespace and can be used on anything, not necessarily `@input`

Honestly I really thought this wasn't a thing but I'm poking around the database now and I can see the following messages with no text or attachments:

```
'SQ': 10744, 
'T': 8672, 
'KN': 1640, 
'EX': 995,
'A': 257, 
'AT': 69,
'TG': 24, 
'FB': 19, 
'TMS': 17, 
'WA': 16, 
'HX': 3, 
```

But I'm still confused.. there are Telegram/Whatsapp/Facebook messages in there yet none of those clients allow users to send empty messages. I don't think most SMS clients allow sending of empty messages either. So are these error cases?

My only concern here is that users think if the simulator can do that then their contacts can do it

**Comment by nicpottier** [comment]
I love how despite doing a query that shows empty messages can happen you say they can't happen. How am I meant to convince you?

Your SMS client may not allow it, but empty messages are indeed possible on some devices and yes they do occur. May be more common on "dumb" phones.

**Comment by nicpottier** [comment]
Also, what does it mean!?!

https://www.quora.com/Whats-the-meaning-when-someone-texts-you-a-blank-text

**Comment by rowanseymour** [comment]
Could you please stop making this personal and accusing me of not believing you.

I'm just saying 1) I didn't know this was a thing and 2) I don't understand how some of these messages exist.

That there are empty messages from channel types whose clients don't allow sending empty messages suggests to me that there is something else going on there - maybe they were sending some additional media that we didn't pick up. 

I also have a hard time believing that users really sent 10744 blank messages on SQ channels and those weren't actually problems in encoding.. the mobile networks etc. 

I just want to understand how these messages came to be.

**Comment by nicpottier** [comment]
But but.. I'm not sure what to say. You can send empty messages. Carriers hand us empty messages over Kannel. It happens! You can search on the internet, people talk about it.

I'm not saying it is common, but blank text messages are a thing and a well built flow should indeed deal with them.

**Comment by nicpottier** [comment]
(note that depending how you did your query some of those hits may be messages with attachments, though likely not the SMS channels)

**Comment by nicpottier** [comment]
(as an aside you also can't send just whitespace in the simulator, ie `  `)

**Comment by rowanseymour** [comment]
> But but.. I'm not sure what to say. You can send empty messages

Because you're not reading my comments. Nobody is debating whether these messages exist. They're in the database. Nobody is debating whether Kannel hands us empty messages. They're in the database.

I'm trying to understand how these message came to be, when it seems to me that messaging clients generally don't allow them.

How are there WhatsApp/Telegram messages when those clients don't allow that? Are we missing something in courier? Are these error cases? Unfortunately those messages are old and no longer have their logs.

I do think it would be potentially confusing if the simulator allows users to do something which their users can't. Like we should explain to users that hey your aggregator might hand us an empty message, but don't expect contacts to be able to send you an empty message because it's not something that most of them can do.

**Comment by nicpottier** [comment]
I understand your clients don't allow it, but others do.

I mean some carriers in Iran apparently REQUIRE it to activate GPRS?
  https://forums.androidcentral.com/google-nexus-4/298778-sending-empty-sms.html

(and hilariously the clients get in the way there!)

The truth is that these do happen in the wild and any open ended question (such as "What is your name?") SHOULD be using "Has some text" to make sure they aren't getting an empty response. So yes, we should be allowing them to test this using the simulator and if having that be in the simulator encourages that behavior then all the better.

**Comment by nicpottier** [comment]
I can send whitespace in Android Messages FWIW but not in Telegram. SMS supports empty though as part of the protocol.

**Comment by rowanseymour** [comment]
> I understand your clients don't allow it, but others do.

I would suspect anyone running a recent Android version can't send empty messages. I get your point - if we _can_ receive empty messages, flows should handle them gracefully. I'm just pointing out the _potential_ confusion there if people build flows which _expect_ an input that most contacts can't send. That is all.
