### ISSUE TITLE
Clicking on completions doesn't complete them

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#763]
When some completions are show (say after typing `@conta`) you can't click on one of the completions and have it complete. I would expect it to do the same as enter (though could see an argument that is should be the same as tab)

**Comment by ericnewcomer** [comment]
Looked at this a bit and first thing I realized is that this completion control doesn't support mousing at all. I feel like maybe this would be a good candidate for re-using rapid components in the editor since this is not a quick fix.

**Comment by nicpottier** [comment]
Are we using components here now? Just saw this again and came to write an issue but saw we were already tracking it.

**Comment by ericnewcomer** [comment]
Not yet. Need to add flow specific completions (results, parent, child, etc), but this is on my shortlist for sure.

**Comment by ericnewcomer** [comment]
This is fixed in the switch to components.
