### ISSUE TITLE
Allow editing of topic on send_msg actions

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#767]
```
topic = event | account | purchase | agent
```

**Comment by nicpottier** [comment]
@ericnewcomer this is one item we need to wrap up before xmas

**Comment by ericnewcomer** [comment]
I presume we want a tab for Facebook a la WhatsApp. Things getting crowded, any feelings on how we should organize these? Seems most that have WhatsApp will also have Facebook enabled. One thought is trying to merge these into a `Channels` tab, but then another drop down on that tab? I dunno, open to ideas here.

<img width="646" alt="Screen Shot 2019-12-13 at 11 49 00 AM" src="https://user-images.githubusercontent.com/211652/70827682-94ff0280-1d9e-11ea-83d4-103f140adcb6.png">
