### ISSUE TITLE
Can't Edit Splits with Many Rows

### ISSUE THREAD

**Issue by putorti** [nyaruka/floweditor#768]
I couldn't scroll this in Chrome, only way to edit it was to delete all the lower rows until the controls came above the window. I believe I filed this before. One solution would be to dock the button bar at the bottom of the window, and allow for internal scrolling on the rules.

<img width="1509" alt="Screen Shot 2019-12-04 at 9 31 15 PM" src="https://user-images.githubusercontent.com/82857/70198724-a0d33080-16dd-11ea-8342-63b972a4e903.png">

**Comment by rowanseymour** [comment]
Side note: we've just added a feature to RP called globals - org-level text values you can access in expressions in flows, messages, campaign events... it wouldn't be an "official" way to use them, but you could stuff JSON in them and then parse it in expressions to do things like lookups.

**Comment by putorti** [comment]
Alright, but this here is still a regression from the old editor. If I switch back, I can do this just fine.

**Comment by ericnewcomer** [comment]
Fixed in #861
