### ISSUE TITLE
URL validation doesn't allow certain expressions

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#772]
For example this URL can't be saved because of the `""`characters:

```
https://example.com?phone=@(url_encode(default(urn_parts(urns.tel).path, ""))
```

I'm not entirely sure validation makes much sense here since anything can be an expression... maybe skip validation when input contains `@`. For example this should be valid..

```
@contact.fields.update_url
```

**Comment by nicpottier** [comment]
Ya since this can contain expressions there really isn't any validation whatsoever we can do here that makes much sense.

**Comment by rowanseymour** [comment]
In fact some say in late 2019 it's best practice to write your webhooks like..

```
@globals.contact_tracker_webhook?phone=@urns.tel
```

🤔
