### ISSUE TITLE
Shouldn't elide lists of groups in group actions?

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#775]
For discussion, but this bit me.. maybe should only elide at something really big like 10?

![Screen Shot 2020-01-07 at 7 38 47 AM](https://user-images.githubusercontent.com/168067/71907411-d32ede00-3120-11ea-882b-fcb4a89debc4.png)

**Comment by rowanseymour** [comment]
Or could at least be clearer that there are more.. instead of "..." say.. **+7 more**

**Comment by ericnewcomer** [comment]
I had originally added this when happening upon massive group adds from customers. Would @rowanseymour 's suggestion have kept you from being bit? These aren't truncated in the old editor, totally amenable to just removing it if you feel it is better overall. Or maybe a combination? show first 10 but then collapsing to **+x more** after that?

**Comment by nicpottier** [comment]
Ya, I understand we want to limit this to SOMETHING, just maybe 3 is too few? Not sure what the magic number is, maybe 5 is just fine then "x more"?

**Comment by rowanseymour** [comment]
5 seems appropriate

**Comment by ericnewcomer** [comment]
K, also changing other elided lists to follow these rules, contacts, labels, urns, etc..

**Comment by ericnewcomer** [comment]
Not really an issue, but those with long enough lists will see their flows reflow on the next load after pushing this.
