### ISSUE TITLE
Split by Expression not honoring negative relative date

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/floweditor#777]
1) Add node for split by expression
2) Add rule for has date greater than with an argument of -30
3) Save, and export

```json
{
   "arguments": [
       "-30"
    ],
    "type": "has_date_lt",
    "uuid": "82ebdeb9-fad3-4ccb-8515-70984246378c",
    "category_uuid": "14b81a3c-b44b-49e0-9dae-c377f09c9926"
}
```

Conversely, wait for response does the right thing:
```json
{
   "arguments": [
      "@(datetime_add(today(), -30, \"D\"))"
    ],
    "type": "has_date_lt",
    "uuid": "1da57cb3-8c57-400e-b5be-de4954d4c8c9",
    "category_uuid": "4c234f17-feb1-4cdf-9f27-f52834c91eb8"
}
```

**Comment by putorti** [comment]
Why is this happening for us on a split by contact field?

<img width="745" alt="PastedGraphic-8" src="https://user-images.githubusercontent.com/82857/72031610-de862480-325a-11ea-9e4b-a961cb83f2a3.png">

<img width="1190" alt="PastedGraphic-9" src="https://user-images.githubusercontent.com/82857/72031611-e0e87e80-325a-11ea-89a7-849354fc80f9.png">

**Comment by ericnewcomer** [comment]
I was having trouble reproducing it with wait for response. I didn’t try it
out on the other splits once I reproduced it in expression. I imagine it’s
on others too. Will make sure to test all splits with rules when fixing it.

**Comment by ericnewcomer** [comment]
Turns out that repro was not actually reliable. Spent a good deal of time on this one and haven't pinned down how to make this happen. Any other clues welcomed.

**Comment by ericnewcomer** [comment]
Finally found a real repro, it's far more subtle:

1) Create any split with a relative date rule, save
2) Open dialog, click cancel
3) Trigger a flow save (move a node, etc)

**Comment by tybritten** [comment]
wow good find. I couldn't seem to figure it out because not all our split flows had it.

**Comment by ericnewcomer** [comment]
@tybritten armed with this knowledge, you should be able to fix this in any of your affected splits by just opening them and clicking save.

**Comment by putorti** [comment]
I actually deleted and recreated flow steps to no effect so, I'm not so sure. We also created a test flow specifically to reproduce it and we were able to without much difficulty, but hopefully this will fix. Perhaps we did an open and cancel.

**Comment by ericnewcomer** [comment]
@putorti if you can reproduce this without doing an open / cancel, then I'd love to see those steps. It's likely a different bug if that is true, so go ahead and open a new issue with specific steps if you can, thanks!

**Comment by LisaBinIL** [comment]
Here's the flow:
https://rapidbot.io/flow/editor_next/b9cbf62a-02b5-46c9-9c72-cfa4744b47b3/#

![image](https://user-images.githubusercontent.com/29188059/72181446-fa9ada80-33ae-11ea-97b0-29d61ef879f8.png)
There's 2 splits.  Both doing the same thing.  As you can see, neither is working

Then I went into each of them and edit/saved.
![image](https://user-images.githubusercontent.com/29188059/72181631-61b88f00-33af-11ea-8eac-e3d3dc9d3de8.png)
Yay.  Both working.

Let's add a new split, that's exactly the same, but let's not touch the other two.
![image](https://user-images.githubusercontent.com/29188059/72181808-bc51eb00-33af-11ea-8485-ed285081e84d.png)
First two still work, new one does not.

Let's go into each split, and edit/cancel:
![image](https://user-images.githubusercontent.com/29188059/72181921-ffac5980-33af-11ea-885c-8e619da79493.png)
Nothing changed.

Now, let's go into the 3rd one and edit/save:
![image](https://user-images.githubusercontent.com/29188059/72181985-210d4580-33b0-11ea-8802-5bd83cb0dc71.png)
First 2 are wrong, 3rd one is now fine.

Let's go back into all 3 and edit/save:
![image](https://user-images.githubusercontent.com/29188059/72182172-8cefae00-33b0-11ea-9e86-bd91de590bb3.png)
Now they're all fine again.

**Comment by ericnewcomer** [comment]
Key here is that you need to trigger a save for the bug to stick. So after canceling you would need to move a node or click save somewhere. From what you are saying here, it sure looks like the same thing unless I'm not reading this right.
