### ISSUE TITLE
Recent messages date format is iso formatted

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/floweditor#784]
This should be formatted in a user friendly way (ideally in the org date format as well)

<img width="160" alt="Screen Shot 2020-01-14 at 12 35 08 PM" src="https://user-images.githubusercontent.com/211652/72380469-51aff080-36ca-11ea-9016-21ef5c7dbc47.png">

**Comment by putorti** [comment]
Was just about to file this, it's unusable as is. Local time or human readable time would be better.

1 min ago
3 mins ago
1 hour ago
etc.

When I make a split change and want to see how things are affected, I just can't tell what's new/old by looking at the ISO date.

<img width="185" alt="image" src="https://user-images.githubusercontent.com/82857/72641863-1bc47380-3939-11ea-9219-972b108363f2.png">
