### ISSUE TITLE
Allow webhook bodies for all HTTP methods

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#786]

**Comment by rowanseymour** [comment]
Started working on this and realized it's trickier than it sounds because we want non-GETs to use the default but not GETs otherwise we'll start sending bodies with everyone's GET requests.

I think the key question is - if you have a POST request and you modify the body, and change it to a GET request, do we keep the [large] body or default it back to empty?

**Comment by nicpottier** [comment]
Give that bodied GETs are pretty rare it seems like the more expected behavior would be to clear the body if you switch from POST to GET.

**Comment by rowanseymour** [comment]
@ericnewcomer what does opt-in mean in this case? TBH I'm starting to feel like this is complicating the UI for a very edge casey feature

**Comment by nicpottier** [comment]
Totally agree this is super edge case and happy to bag it, but can't we just change the "Post Body" tab to just be "Body" and always show it? It is empty for the GET case and gets cleared whenever you switch to GET from POST. When you switch to POST/PUT it is set to our default payload.

**Comment by ericnewcomer** [comment]
That works for me.

**Comment by rowanseymour** [comment]
I can do that - downside is just that someone potentially makes a bunch of changes to a POST payload and then loses them toggling to GET and back to POST.

**Comment by rowanseymour** [comment]
Or maybe they intend to make a POST with a body so they edit the body, then change to POST, and they lose their body

**Comment by nicpottier** [comment]
Yep, I'm comfortable with that for the time being.

**Comment by chris-erickson** [comment]
Since I pushed for the feature, I would be completely OK with destroying your work switching between types.  Something people will learn quickly and I don't think people will be toggling this often.
