### ISSUE TITLE
Default webhook headers not right

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/floweditor#793]
Should be setting `Accept` instead of `Content-Type` to `application/json`

**Comment by rowanseymour** [comment]
Legacy flow migration sets `Content-Type` on the action if the method is `POST`.. we're also setting a default payload at that point which we know is JSON. I think we want to set both because a endpoint could need `Content-Type` set..

**Comment by nicpottier** [comment]
For `POST`s, especially for legacy ones we should set `Content-Type` for sure. But with `Accept` as well for everything (by default)

**Comment by ericnewcomer** [comment]
Yes, POSTs also need content type.
