### ISSUE TITLE
Recent messages popup should always be top

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#836]
<img width="475" alt="Captura de Pantalla 2020-03-03 a la(s) 10 18 48" src="https://user-images.githubusercontent.com/675558/75789915-6dce2680-5d38-11ea-9bac-6a72f2661f3d.png">

**Comment by ericnewcomer** [comment]
Exits are now portaled, so can no longer reproduce this. Let me know if you still see it.
