### ISSUE TITLE
Translate Drawer

### ISSUE THREAD

**Issue by nicpottier** [nyaruka/floweditor#851]
Related to https://github.com/rapidpro/rapidpro/issues/1176 in complicated flows it can become difficult to know which parts of a flow have been translated and which still need translation.

One simple idea would be simply to have a checkbox / percentage displayed somewhere to tell you what your progress is in translating the flow, but doesn't go far enough for two reasons:
 1. in big flows is can be hard to find the node that is missing a translation
 2. users may not care about rulesets being translated so having a single percentage is probably not enough

One idea around both would be to add a "Translate" drawer similar to the current "Issues" drawer that shows a list of all the text items that need translation in the current language. When you click on it you are taken to the node to enter the translation. That drawer could group the translations based on whether they are parts of splits or normal messages to make it easier to draw a line on what is needed to translate since that is the typical distinction.

That said, even with this it would probably be useful to have a top level indication that a language is fully translated (excluding splits) in the language listing at the top of a flow.

**Comment by ericnewcomer** [comment]
#856
