### ISSUE TITLE
Two-axis scrolling

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/floweditor#853]
We added horizontal scrolling, however, vertical scrolling is window-based and horizontal is an overflowed div. Would be nice to allow two-axis scrolling (which likely needs to scroll within the same container for both directions). Note, this doesn't affect non-trackball mouse users. It's rather obvious on a trackpad though.

This would also ensure the horizontal scrollbar would be present without having to first scroll down. One consideration is that window-based scrolling is nice in that the header is not sticky, but perhaps some sort of sticky scroll solution could be considered for the main editor pane.

**Comment by mdshamoon** [comment]
@ericnewcomer our users at Glific were also facing some issues on scrolling to the bottom and then get a horizontal scroll. We made some changes to allow both scrolls on the screen.

Here is the link to the file changes that we did. https://github.com/glific/floweditor/pull/32/files
Let me know if these changes look fine and I can create a PR here with these changes.

**Comment by ericnewcomer** [comment]
This has been fixed.
