### ISSUE TITLE
Issue tracking mixing up legacy extra and invalid regex

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#854]
This is a flow that uses `@legacy_extra` which I think we said we'd ignore in the editor for now, but the issue gets reported as an invalid regex

<img width="967" alt="Captura de Pantalla 2020-04-06 a la(s) 11 37 00" src="https://user-images.githubusercontent.com/675558/78582487-f38f3700-77fa-11ea-8418-dd831b613568.png">

**Comment by ericnewcomer** [comment]
Ha, hadn't seen this issue, but literally just came here to log this issue from a customer. Another thing I noticed is these are currently only showing up on page reload. If you just open/save them they vanish and return on page reload. Which suggests the metadata returned on save and that which comes on load are not identical.

**Comment by rowanseymour** [comment]
Looks the same from a flow I'm checking out now...

GET to flow/revisions returns `{"definition": {...}, "metadata": {...}}` 
POST returns `{"revision": {...}, "metadata": {...}}`

Metadata is same on both but editor isn't finding it in second case
