### ISSUE TITLE
Can translate empty flows

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#858]
You can get yourself into a bit of weird state if you switch languages on an empty flow and then hit create message..

<img width="1098" alt="Captura de Pantalla 2020-04-10 a la(s) 12 11 46" src="https://user-images.githubusercontent.com/675558/79009168-89410400-7b24-11ea-9477-f84755d30fd4.png">

**Comment by ericnewcomer** [comment]
Fixed by #856
