### ISSUE TITLE
Reordering tests in Split by Flow Result

### ISSUE THREAD

**Issue by putorti** [nyaruka/floweditor#875]
See this behavior in Chrome:
[reorder-ui.mov.zip](https://github.com/nyaruka/floweditor/files/4565689/reorder-ui.mov.zip)

**Comment by ericnewcomer** [comment]
That is super weird. Have you seen this on other flows? Can you reproduce it from an empty flow with specific steps?

**Comment by ericnewcomer** [comment]
Tried again and still can't reproduce this without more detail. Also, this widget has changed quite a bit since then, so perhaps it no longer happening as well?
