### ISSUE TITLE
Unable to edit splits with more tests than room in browser window

### ISSUE THREAD

**Issue by putorti** [nyaruka/floweditor#876]
The old UI would dock the end of the window to the bottom of the browser and allow scrolling of the rules, new one still doesn't. Once the old editor goes away, we'll be stuck unable to edit these, unless we zoom out to 50% or 25% etc.

<img width="771" alt="image" src="https://user-images.githubusercontent.com/82857/80829188-a82b3700-8bb4-11ea-9637-f76160a71615.png">

**Comment by ericnewcomer** [comment]
Which version are you running? This was added in https://github.com/nyaruka/floweditor/pull/866

**Comment by ericnewcomer** [comment]
This screenshot looks like the old version, reopen if there is still an issue.
