### ISSUE TITLE
Modify default timeout value for file upload requests

### ISSUE THREAD

**Issue by paulobernardoaf** [nyaruka/floweditor#887]
The default timeout value set for an Axios request, on floweditor, is 30000 (30 sec). On a file upload request, this timeout could be easily exceeded.
How about setting a different timeout value for that kind of request directly on the [post method request](https://github.com/nyaruka/floweditor/blob/master/src/components/flow/actions/sendmsg/SendMsgForm.tsx#L250)? On an environment variable or a static number.

**Comment by johncordeiro** [comment]
@ericnewcomer ,what do you think about it? what usually happens is that depending on the user connection, even for small file uploads it reach 30 seconds.

**Comment by ericnewcomer** [comment]
Don’t particularly want to raise it but I can make it a configurable option.

**Comment by matmsa27** [comment]
Hi @ericnewcomer , Yes, configurable is a good way, how would be that configuration?

**Comment by ericnewcomer** [comment]
It’d be on the configuration object for the flow editor where it is embedded. There would be a separate task in RP to make that embed be configurable via settings.

**Comment by matmsa27** [comment]
Hmm, which service will host the variable to FlowEditor read

**Comment by matmsa27** [comment]
Hi @ericnewcomer , do you have any updates about how can go ahead with this?

**Comment by ericnewcomer** [comment]
Sorry I’ve been out recently, but I’ll try to get to this during the week!

**Comment by matmsa27** [comment]
Hi @ericnewcomer , no problem. If there is anything we can help, we are available
