### ISSUE TITLE
Blocking contacts

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#889]
For https://github.com/rapidpro/rapidpro/issues/607 I've so far added a generic action to the engine to change contact status https://github.com/nyaruka/goflow/issues/939

But not completely sure how best to surface that in the editor.

1. Add to `Update Contact`: you would select `Status` in the same way you select `Language` or `Name`.. and then select one of `Active`, `Blocked` or `Stopped`
2. Explicit UI node types for `Block Contact`, `Stop Contact`.. and maybe  `Activate Contact` ?

Downside of 1 is whether users looking to block a contact would ever think to look for it there. Downside of 2 is adding to the mega list of node options.

**Comment by nicpottier** [comment]
Ya, the mega list of possible actions is mega. I do wonder if we are going to have to rethink that at some point as 1) definitely seems like the right approach here but as you said then decreases discoverability. Maybe being clever about some kind of "searching" in that list could help but that feels cheap.

In any case, I think 1) is right. I hadn't previously thought we would add `Stopped` in there as that is something the contact themselves control but now that I'm thinking of it it does seem to make sense that we allow flow authors to manually stop contacts based on some action the contact is making.

Related, do we think Contact deletion will its own action?

**Comment by rowanseymour** [comment]
I think stop makes sense where it's clear the contact wants to stop communicating and you want to record that and not confuse it with the contact sending you spam and you blocking them. That said, it's a little odd in that the onus is on you the flow designer to record that intention correctly.. so I think the select options need to explain the meaning, e.g. something like..

```
* Blocked (the contact is sending spam etc)
* Stopped (the contact is opting out of communication)
```

I'm still not entirely convinced about making contact deletion part of flows (guess we should chat!) but I don't think it would be part of this node if it were.

**Comment by rowanseymour** [comment]
Re the mega list.. if we said we only allow Block and Stop then I could imagine having one extra item in the mega list like 

```
Block or stop the contact
```

Then on that modal you pick between the two.. @ericnewcomer thoughts?

**Comment by ericnewcomer** [comment]
One quick thought on this is that `Blocked` vs `Stopped` sure sound like the same thing to the naive user. I feel like maybe `Stopped` should be presented to the user as `Opted Out` and they should be able to put people in that status as well. Only reservation I have there is it suggests maybe they are opted in by virtue of not being in that list. I guess there is a difference between an explicit opt out and not being opted in yet though, so maybe thats okay. 

I think update status with a list of options is an acceptable solution.

```
Update Contact
  - Set Status
  - [ Active, Opted Out, Blocked ]
```

Corollary thought, even though it can be modeled with groups, this does suggest maybe making `Opted In` a system level status is at least worth discussing.

**Comment by rowanseymour** [comment]
An issue there is that we would want this terminology to match what they could see in expressions. We currently have...

`@contact.status = active|blocked|stopped`

Tho today you will always see `status = active` because we don't allow blocked and stopped contacts to be in flows. We could change stopped in expressions to `optedout`, `opted_out` (?), but I think I'd prefer just to explain in the dropdown that stopped is opted-out, something like...

```
* Blocked - we no longer want to communicate with the contact
* Stopped - the contact is opting out of communication
```

Re opt-in, obvious there's a 6.0 issue for this so we should discuss. My initial thought would be it's not really a status. Users want a way to model contacts opting-in that let's them see things like when a user did that. So even if a user later opts out, we would still want a record of how/when they opted-in. It also might not be a single thing - contacts might opt-in to various different streams of communication within the same org.

**Comment by ericnewcomer** [comment]
Had the same thought re multiple kinds of opted-in.. I don't think I want it to be a first class thing, I just want to make sure we are at least thinking about it. What with TCPA and all, it seems pointing users towards getting that opt-in in a more formal way isn't the worst thing. But ya, feel the same about how that fits in and the amount of rope reduction it suggests.

We can discuss that there (can you link it here for reference?) and stop this threadjack here. I think we are in agreement that a dropdown of status options is the way to go for this in any case.

Some related issues:
https://github.com/rapidpro/rapidpro/issues/392
https://github.com/rapidpro/rapidpro/issues/400

**Comment by nicpottier** [comment]
Intuitively I kinda agree that "opted in" feels like a status though. The problem is that status implies a single state at a time, which even now isn't entirely true. It is technically possible for a user to be both stopped and blocked for example, at least in the real world. (IE, a user blocks them and they also send "stop" so Twilio stops them)

Even with that though maybe we could think of it as a spectrum?
`stopped <-> blocked <-> active <-> opted in`

Only argument for that as you said people want to know the dates of these status changes (when did they opt in? when did they opt out?) and I could see us maybe having a model around "status changes" that could be used for that. Which would then be a date, the status we changed to and maybe who changed it.

So that feels like maybe that could be nice and clean in a way.

The wrench there is that I believe Chris mentioned in his request that he wants DIFFERENT types of opt-in's, for say different programs within a single workspace. So that kinda torpedos the idea of us having a single opt in.

**Comment by nicpottier** [comment]
So in summary, ya, I think stopped is better than `opt out` only because the analog of `opt in` can't be a status.
