### ISSUE TITLE
Enable Portuguese translation

### ISSUE THREAD

**Issue by paulobernardoaf** [nyaruka/floweditor#891]
Hello guys! I've noticed that Portuguese translation is not enabled in [i18n initialization](https://github.com/nyaruka/floweditor/blob/master/src/config/i18n/index.js#L14), but there's already a [Portuguese resource](https://github.com/nyaruka/floweditor/blob/master/src/config/i18n/pt/resource.json) for i18n.

After enabling it:
![image](https://user-images.githubusercontent.com/30026625/88425891-9083d900-cdc6-11ea-9057-d30714ec9ca5.png)
The translation works but the [i18next language detector](https://github.com/nyaruka/floweditor/blob/master/src/config/i18n/index.js#L21) use the Browser language as a target language, or when `?lng=pt` is used on the URL.

There's also a [Transifex project](https://www.transifex.com/rapidpro/flow-editor/) for the flow editor, if the Portuguese translation reaches 100% it would be automatically merged into the flow editor and enabled in rapidpro?

What should be done in rapidpro to enable the flow editor translation? Since the language is not defined by the browser language but by the rapidpro settings.

**Comment by rowanseymour** [comment]
Have anyone addressed this issue with the Portuguese translation https://github.com/nyaruka/floweditor/issues/806 ?

**Comment by johncordeiro** [comment]
hey @rowanseymour  we're updating Transifex with the right variable names in the translation.

**Comment by paulobernardoaf** [comment]
Hello @rowanseymour the Portuguese translation was updated on [Transifex](https://www.transifex.com/rapidpro/flow-editor/dashboard/), how do we proceed to add it here on the git repo?

**Comment by rowanseymour** [comment]
I've made a PR at https://github.com/nyaruka/floweditor/pull/892.. @ericnewcomer can confirm if it looks right

**Comment by rowanseymour** [comment]
I changed the language code from `pt` to `pt-br` to match the language as configured in RapidPro but I'm not sure how language gets passed to the editor.
