### ISSUE TITLE
Flow Result Truncation

### ISSUE THREAD

**Issue by putorti** [nyaruka/floweditor#894]
![image](https://user-images.githubusercontent.com/82857/89309176-1282c600-d641-11ea-8c38-851704786e18.png)

So this result is actually cut off after the word **kinds** when used in a webhook, but it's not clear in the UI that the result would be truncated at all. When I copy and paste directly into the body of the webhook POST, it works just fine.

**Comment by ericnewcomer** [comment]
Thanks for the issue. This isn't necessarily straight forward as the max length isn't always known as variables can force truncation in different locations with the same body of text. That said, I agree we should give some indication of the behavior here. Perhaps a max length that matches the max in the engine but additionally a warning if they are near the max and there are variables in the body.

**Comment by rowanseymour** [comment]
It's a side issue but it seems like the UI should be trimming the value displayed here to maybe a few lines and adding "..." - like for long webhook URLs https://github.com/nyaruka/floweditor/issues/882

**Comment by ericnewcomer** [comment]
Yes, agree. As part of this the summary should also be shortened.

**Comment by ericnewcomer** [comment]
The fix in #992 here is to truncate the view of this text. This is not related to the issue of webhook urls having an upper limit (which is not related to the save result action)
