### ISSUE TITLE
Alignment issue on call webhook action

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#899]
<img width="224" alt="Captura de Pantalla 2020-08-14 a la(s) 12 36 48" src="https://user-images.githubusercontent.com/675558/90293885-c149b200-de4a-11ea-83b5-595d313abf86.png">

**Comment by ericnewcomer** [comment]
Fixed https://github.com/nyaruka/floweditor/commit/1b7e77476a75e3215b16740d5c06fc8247e161e1
