### ISSUE TITLE
Deleting "Enter a New Flow" step leaves behind an artifact

### ISSUE THREAD

**Issue by putorti** [nyaruka/floweditor#907]
Video here: [ui-error.mov.zip](https://github.com/nyaruka/floweditor/files/5227243/ui-error.mov.zip)

**Comment by putorti** [comment]
Still: ![image](https://user-images.githubusercontent.com/82857/93254609-9662be80-f766-11ea-8fb6-e1fe1c662511.png)

**Comment by ericnewcomer** [comment]
Hi @putorti not sure what version this is, but I am unable to reproduce this. Can you make it happen on TextIt?

**Comment by ericnewcomer** [comment]
@putorti just checking in here, were you able to reproduce this on TextIt?

**Comment by putorti** [comment]
@ericnewcomer It seems there's a minimum monthly fee now to use it...

**Comment by ericnewcomer** [comment]
Ha! There's a free trial too. :)

**Comment by ericnewcomer** [comment]
Closing this for now due to my inability to reproduce it.
