### ISSUE TITLE
Odd UI glitches in Chrome

### ISSUE THREAD

**Issue by putorti** [nyaruka/floweditor#909]
<img width="882" alt="image" src="https://user-images.githubusercontent.com/82857/93714735-aa296e80-fb32-11ea-97c0-9080e38d8127.png">

**Comment by nicpottier** [comment]
This is super weird and I have a hard time imagining what we could be doing to cause this. Is this consistent? Looks like a Chrome bug to me. @ericnewcomer ?

**Comment by ericnewcomer** [comment]
I have never seen this. Looks like some kind of crazy browser paint bug.

**Comment by ericnewcomer** [comment]
Unable to reproduce this, closing. Please reopen if you think it's something we are causing and can determine repro steps.
