### ISSUE TITLE
Issues with router cases

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#919]
* the re-order icon appears for all cases but doesn't work for the last case
* alignment issue as shown below

<img width="615" alt="Captura de Pantalla 2020-10-13 a la(s) 09 16 04" src="https://user-images.githubusercontent.com/675558/95872820-dc467e80-0d34-11eb-95ab-06e9334c6368.png">

**Comment by ericnewcomer** [comment]
The last one not be sortable is actually by design since it is the form for adding a new case and is always at the bottom.

**Comment by rowanseymour** [comment]
Ok that makes sense but the reorder control appears on hover so it looks like it should be draggable
