### ISSUE TITLE
Add Trigger Behavior to Triggers Page

### ISSUE THREAD

**Issue by putorti** [nyaruka/floweditor#924]
Improvement idea, no way to know whether the trigger is "only" or "starts with" unless you click in, that's a lot of clicking. Seems there's more than enough room to display it in the list.

<img width="888" alt="image" src="https://user-images.githubusercontent.com/82857/96932226-8f794b00-148c-11eb-97e3-c96f5f83860c.png">

**Comment by rowanseymour** [comment]
Seems reasonable but this is not part of the floweditor repo (unfortunately I can't transfer this issue to rapidpro/nyaruka because you can only transfer issues to repos in the same org)

**Comment by ericnewcomer** [comment]
Yup, issue needs to be openend on https://github.com/rapidpro/rapidpro/issues
