### ISSUE TITLE
Make message attachments localizable

### ISSUE THREAD

**Issue by pankaj-ag** [nyaruka/floweditor#927]
Hello, thanks for the great library. 

I just wanted to check if there is a way to send different attachments for different languages. We want to send the same video in two different languages.

**Comment by dlobo** [comment]
So basically support to use different attachments for different translations:

So message in English has the English attachment, message in Hindi will have the hindi attachment

We don't think its present in the code right now. If a relatively not-too-complex project, we'd be happy to contribute resources to make this happen

**Comment by dlobo** [comment]
any hints on this please?

**Comment by nicpottier** [comment]
This came up with one of our customers as well so we may want to consider adding this as an option.

@dlobo we don't accept PRs on this repo, but rather keep all development internal to Nyaruka.

**Comment by rowanseymour** [comment]
Note this has always been supported in the engine.. for those who use that!

**Comment by dlobo** [comment]
can you elaborate on supported by the engine? In what way, if the user cannot use different attachment urls

**Comment by dlobo** [comment]
> @dlobo we don't accept PRs on this repo, but rather keep all development internal to Nyaruka.

No worries. We continue to remain grateful for keeping this open :) Has been super helpful to us

**Comment by dlobo** [comment]
Just an update with a really not-so-nice workaround (for now). we are experimenting with adding the URL and type at the end of the localized text and then our processor can extract it and replace it for the existing attachment. Not a great solution, but a lot better for our users than creating new flows for a language

**Comment by pankaj-ag** [comment]
Hello, 
To fix the issue we enabled the attachments section for all the languages. Currently, this is in our [forked branch](https://github.com/glific/floweditor). 
Here is the commit with changes. 
https://github.com/glific/floweditor/pull/5/commits/98cf3d88d339a85f6f8b15e022e0838422249a26

Let us know if you have any thoughts or suggestions here.

**Comment by ericnewcomer** [comment]
This was added a while back, closing.
