### ISSUE TITLE
Add sticky notes

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/floweditor#93]
We need to implement the old version of sticky notes on double click.

One thing that is sorely lacking in the old editor is a way to create brand new nodes which can currently only be done by dragging from an existing node which isn't always possible or prudent on a live flow. One thought is that instead of immediately creating the sticky note on double click, we could present a context menu in place that shows options to either create a new note or a new node.

**Comment by ycleptkellan** [comment]
Thats a cool idea. Wondering what sorts of ideas you have for the context menu component. I'm picturing a popover at click location that presents two choices, node (opens node editor) or note (renders a note component).

**Comment by ericnewcomer** [comment]
Discussed this a bit further with @nicpottier and wanted to capture that discussion here. The result of that discussion is that the context menu is less important with our ability to add and splice nodes into the flow present in the new editor. Adding a context menu maybe very well add unnecessary complexity for the user, especially since we are way nicer about adding actions or splits to existing nodes without forcing them to drag.

**Comment by ycleptkellan** [comment]
Want to make sure I'm following, what's the plan for making adding actions and splits nicer? Does this mean we aren't going to provide a way to add a new node without dragging from an existing node? 

Also, what conclusion did you come to about discoverability? Seems to me like one of the least obvious features in the editor, but then again I do see flows with sticky notes in the wild...

**Comment by ycleptkellan** [comment]
Ah, I understand now thank you. That might be a good question to pose to power users, would it make sense to set up a feedback-gathering process for things like this?

**Comment by ericnewcomer** [comment]
Post on http://feedback.textit.in ?

**Comment by ycleptkellan** [comment]
Worth a try, though I'm hoping we'll reconsider UserVoice at some point. I'll make a note to look at Intercom's offerings/suggestions as well JIC.
