### ISSUE TITLE
@results and @contact auto populate dropdown is missing. 

### ISSUE THREAD

**Issue by pankaj-ag** [nyaruka/floweditor#936]
In the Earlier version of the flow editor, we show that if someone types **@results** or **@contacts**  in any input box it shows a dropdown of all the available values and variables. 

But it's not available on the new version. Can you please let me know in case I am missing something here?

![image](https://user-images.githubusercontent.com/10670690/101323690-1d6b9280-388f-11eb-950c-a10da1ca3a9c.png)

**Comment by rowanseymour** [comment]
It's just that demo page that is broken. The editor still has auto-completion.

**Comment by pankaj-ag** [comment]
I saw that it's was working on v1.10.5 but not on v1.11.0. 
I think when we move it to temba-completion. 
I also tried it with lambda on the latest release but it's not working. 

Please let me know in case I need to make any changes in the compilation API response or missing something here.

**Comment by pankaj-ag** [comment]
After looking at the code we finally realise that we have to initialise the tamba library to get it working. 

Thanks for all your support 🎉
