### ISSUE TITLE
Autocomplete helper is off screen

### ISSUE THREAD

**Issue by putorti** [nyaruka/floweditor#937]
Seems to be happening in the call web hook flow step.

<img width="1253" alt="image" src="https://user-images.githubusercontent.com/82857/101849520-0f2ea800-3b15-11eb-9998-378589ace00b.png">

**Comment by ericnewcomer** [comment]
<img width="780" alt="Screen Shot 2021-03-26 at 10 41 17 AM" src="https://user-images.githubusercontent.com/211652/112671801-e14d4500-8e1f-11eb-8268-0a6722104107.png">

This looks to have been resolved. If you are still seeing this on the current version please reopen.
