### ISSUE TITLE
Editing a message moves the cursor to the end of the message

### ISSUE THREAD

**Issue by abhi1203** [nyaruka/floweditor#938]
Here's a short video to see the error
[Screen Recording 2020-12-11 at 11.35.39 AM.zip](https://github.com/nyaruka/floweditor/files/5677294/Screen.Recording.2020-12-11.at.11.35.39.AM.zip)

**Comment by rowanseymour** [comment]
Which version of RapidPro are you using? This sounds a like a bug that briefly existed in 6.0.x but is fixed

**Comment by pankaj-ag** [comment]
@rowanseymour we are using v1.11.8 of the flow editor. 

Do you remember in which version of floweditor you guys fixed this issue?

**Comment by rowanseymour** [comment]
Not sure but it was a fix in the underlying components library https://github.com/nyaruka/temba-components/issues/35

**Comment by rowanseymour** [comment]
So we're able to reproduce this now - it seems there's an issue in the latest editor when send message actions have special quote characters `’` like what I see in your video.

**Comment by rowanseymour** [comment]
Fixed in https://github.com/nyaruka/temba-components/pull/43
