### ISSUE TITLE
Support for a delay node

### ISSUE THREAD

**Issue by mdshamoon** [nyaruka/floweditor#945]
Hey guys, thanks for this great library. 

We were hoping to have a delay node for our use case which adds a time delay between two messages. 
So we experimented with the forked version of the repository and got something like below by some additions to the repository. Let us know your thoughts on these [changes](https://github.com/glific/floweditor/pull/7/files?file-filters%5B%5D=.css&file-filters%5B%5D=.js&file-filters%5B%5D=.map&file-filters%5B%5D=.scss&file-filters%5B%5D=.ts&file-filters%5B%5D=.tsx&file-filters%5B%5D=.txt#diff-4ad3bb7ab4034ae9edf4cb2704b09c9854d63b4a6b649150cd6dcaef02f63806).

Basically, we created a new action called delay and store that in revisions in the following format:

```
"nodes": [
    {
      "uuid": "3ea030e9-41c4-4c6c-8880-68bc2828d67b",
      "actions": [
        {
          "type": "wait_for_time",
          "uuid": "a77035ac-4111-42c5-b1a0-6701aef9d67e",
          "delay": "time in seconds"
        }
      ]
    },
]
```

Also, can we have a feature like this in the floweditor

![image](https://user-images.githubusercontent.com/32592458/102785539-2ba7cb80-43c4-11eb-97b0-c3915f9329c5.png)
![image](https://user-images.githubusercontent.com/32592458/102785577-39f5e780-43c4-11eb-8afb-7de5dc1af17d.png)

**Comment by rowanseymour** [comment]
We've often been asked for an action like this tho usually the use case is that users want to slow down outgoing messages to make the interaction with the contact feel more like a human interaction. So we're talking about delaying by seconds rather than days. The difficult part isn't adding this to the editor, but what it means in the engine. What does this action do if the contact sends a message whilst it is waiting?

**Comment by nicpottier** [comment]
Ya, this approach was considered early on, but it doesn't lend itself well to flexible systems. In RapidPro this type of delay (days/hours) is handled via campaigns, which then give you a ton of flexibility in bringing people in and out of the campaign or rescheduling the event etc.. The problem with long waits in flows is there really isn't any good way to adjust that wait if you change your mind or the status of the contact changes etc.. campaigns let you do this by either changing the group membership or the relative date.

**Comment by mdshamoon** [comment]
@rowanseymour we are still experimenting with it. Initially, we were thinking that no other action will run in the waiting time even if the contact sends a message back. 

Thanks, @nicpottier for pointing us towards campaigns. We will surely have a look at it.
