### ISSUE TITLE
Allow name matching expressions in Add To Group and Add Labels actions

### ISSUE THREAD

**Issue by rowanseymour** [nyaruka/floweditor#959]
In the engine, Add To Groups, and Add Labels allow matching by name, but you can't use an expression as a group in the editor.

<img width="289" alt="Captura de Pantalla 2021-01-27 a la(s) 10 03 07" src="https://user-images.githubusercontent.com/675558/106009997-fce9d880-6086-11eb-9fb6-ad7e66d4541b.png">

I thought this was something we fixed a while ago or maybe that was groups as destinations for broadcasts/new flow starts. I don't even love this as a feature but it does save users creating mega splits around group membership like https://app.intercom.com/a/apps/l6e7tr01/inbox/inbox/conversation/20798300033689

**Comment by ericnewcomer** [comment]
Looking at this, I see it isn't there for labels, but it looks like it is on `Add to Group`. Can you show me how to get in the state from your screenshot @rowanseymour ?

**Comment by rowanseymour** [comment]
Ahh I remember I got confused by this before (a user too who reported not being able to do this)... I'm forgetting that you have to tab once you've written an expression, since this is a multi-select box. I wonder if there's a way to make this more obvious..

**Comment by rowanseymour** [comment]
I mean it's fairly intuitive if you approach this control as something to add multiple items to, maybe you select something from the dropdown by tabbing, then you add an expression, by tabbing as well. But if you're only writing an expression for a single group, it's easy to think you're dealing with a regular input field. 

And then also tab means auto-complete when that is showing.. so you need to do tab, enter, tab

<img width="284" alt="Captura de Pantalla 2021-02-01 a la(s) 15 20 43" src="https://user-images.githubusercontent.com/675558/106513519-19c84680-64a1-11eb-8597-d1409eaf35e7.png">

**Comment by ericnewcomer** [comment]
Agreed, it's a bit confusing if you don't realize it is a field for multiple labels (which is likely never going to be multiple in the expression case. Issue here is that the expression could be a full expression with parens, functions, etc, so I don't want selection to be performed until they signal it is done. Maybe we special case if you tab and have no open parens yet to perform the selection? I don't think what we have to be super terrible in any case since it is flexible to all cases and this is a pretty goofy feature to begin with.

**Comment by rowanseymour** [comment]
Certainly no obvious way to improve this. Maybe instead of changing the entry mechanism, the validation could be clearer? Currently you can type an expression, hit OK and nothing happens.. no error message appears: 

<img width="294" alt="Captura de Pantalla 2021-02-01 a la(s) 17 07 25" src="https://user-images.githubusercontent.com/675558/106524013-fa84e580-64af-11eb-815f-4f8e20b25b0f.png">

It's not unless you hover over the field that a tooltip appears:

<img width="283" alt="Captura de Pantalla 2021-02-01 a la(s) 17 07 08" src="https://user-images.githubusercontent.com/675558/106524029-fe186c80-64af-11eb-851d-7c56bcb4f81b.png">

Which isn't particularly helpful because there's input in that field.. that looks valid

**Comment by rowanseymour** [comment]
This was adjusted in temba-components to submit on enter for simple variables
