### ISSUE TITLE
between does not work with a flow variable

### ISSUE THREAD

**Issue by tybritten** [nyaruka/floweditor#965]
Example:
using `between` with `results.count` shows 'must be a number':
![image](https://user-images.githubusercontent.com/1933680/108233189-85511b80-7111-11eb-8480-25db0e19e873.png)
But below/above work fine:
![image](https://user-images.githubusercontent.com/1933680/108233324-a74a9e00-7111-11eb-9c92-34be55694e65.png)

Can repro in TextIt

**Comment by ericnewcomer** [comment]
Verified this behavior. Haven't looked but presumably expressions are allowed here and we need to loosen the editor's validation here. Will investigate.
