### ISSUE TITLE
Operator filters aren't right in some cases

### ISSUE THREAD

**Issue by ericnewcomer** [nyaruka/floweditor#974]
1) IVR flows should only filter out text based rules on the multiple digit router
2) Location based rules should only be visible if the user has a country set

**Comment by ericnewcomer** [comment]
Number one for ivr routers has been addressed

**Comment by nicpottier** [comment]
Having `matches regex` on a mutiple digits router would still be useful. (from a customer request)

**Comment by rowanseymour** [comment]
These are done and we re-added has_text and has_pattern for wait for digits routers
