### ISSUE TITLE
Make particular flow arrow (and children) inactive if not yet ready for deployment

### ISSUE THREAD

**Issue by jk979** [nyaruka/floweditor#989]
Example: 3 options, 2 of the options are ready for deployment, 3rd option is not fully ready, but built on the flow editor. User in flow editor should be able to right-click the flow arrow of 3rd option and make it inactive, and it becomes red in the UI showing that it is currently inactive. <-- This can help clarify which sub-flows are still under development while allowing for deployment of the rest of the flow. User won't have to delete the inactive flow and recreate it later when it's ready.

**Comment by ericnewcomer** [comment]
Have you looked into sticky notes to denote which things are still in active development? You can create them by double clicking on the background. I'd recommend a combination of that and not adding the rule to split until you are ready.
