### ISSUE TITLE
Add module export

### ISSUE THREAD

**Issue by rafaelbreno** [nyaruka/floweditor#998]
I tried to implement FlowEditor in a React project, but unfortunately it was little more difficult than the normal, what I've done until now:
1. > npm install @nyaruka/floweditor
2. Inside my project I would need to:
    1. Read the manifest
    2. Import the assets based on the manifest
    3. Use the function `window.showFlowEditor()`
3. Those are the same steps that are implemented on `rapidpro` and I'd to follow the same steps to import a React component inside of a React project  

My request is, is possible to import as `import { FlowEditor } from '@nyaruka/floweditor'`(as a Component)? Or would be a feature request?

**Comment by ericnewcomer** [comment]
We don't have plans to make integration outside of RapidPro any different. I would recommend a public fork if you want to support different packaging.
